-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "tundra"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { link = "Constant" })
hi(0, "@comment.error", { bg = "#d1242f", fg = "#ffffff" })
hi(0, "@comment.hint", { bg = "#d0d7de", fg = "#ffffff" })
hi(0, "@comment.info", { bg = "#0969da", fg = "#ffffff" })
hi(0, "@comment.todo", { bg = "#d0d7de", fg = "#ffffff" })
hi(0, "@comment.warning", { bg = "#9a6700", fg = "#ffffff" })
hi(0, "@conceal", { link = "Conceal" })
hi(0, "@constant.builtin", { fg = "#0550ae" })
hi(0, "@constant.builtin.rust", { fg = "#953800" })
hi(0, "@constant.html", { link = "@tag" })
hi(0, "@constant.macro", { link = "Macro" })
hi(0, "@constructor", { fg = "#953800" })
hi(0, "@constructor.lua", { fg = "#1f2328" })
hi(0, "@diff.delta", { link = "diffChanged" })
hi(0, "@diff.minus", { link = "diffRemoved" })
hi(0, "@diff.plus", { link = "diffAdded" })
hi(0, "@function.builtin", {})
hi(0, "@function.builtin.bash", { fg = "#cf222e" })
hi(0, "@function.builtin.lua", { fg = "#0550ae" })
hi(0, "@function.builtin.make", { link = "@constant" })
hi(0, "@function.call.bash", { fg = "#0550ae" })
hi(0, "@keyword.directive.rust", { fg = "#0550ae" })
hi(0, "@keyword.exception", { fg = "#0550ae" })
hi(0, "@keyword.function", { fg = "#cf222e" })
hi(0, "@keyword.operator", { fg = "#cf222e" })
hi(0, "@keyword.storage.lifetime.punctuation.rust", { link = "@markup.list.rust" })
hi(0, "@keyword.storage.lifetime.rust", { link = "@tag.rust" })
hi(0, "@label", { link = "@tag" })
hi(0, "@label.ruby", { fg = "#0550ae" })
hi(0, "@label.vimdoc", { link = "@keyword" })
hi(0, "@lsp.type.class", { link = "@function" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.interface", { link = "@interface" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hi(0, "@lsp.type.property", {})
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.type.variable.lua", {})
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@markup.environment", { fg = "#cf222e" })
hi(0, "@markup.environment.name", { fg = "#6639ba" })
hi(0, "@markup.heading.1.delimiter.vimdoc", { bg = "#ffffff", fg = "#ffffff", nocombine = true, sp = "#1f2328", underdouble = true })
hi(0, "@markup.heading.2.delimiter.vimdoc", { bg = "#ffffff", fg = "#ffffff", nocombine = true, sp = "#1f2328", underline = true })
hi(0, "@markup.heading.html", { fg = "#1f2328" })
hi(0, "@markup.italic", { fg = "#1f2328", italic = true })
hi(0, "@markup.link", { fg = "#1f2328", underline = true })
hi(0, "@markup.link.label", { link = "Special" })
hi(0, "@markup.link.uri", { fg = "#0550ae", italic = true, underline = true })
hi(0, "@markup.list", { fg = "#0550ae" })
hi(0, "@markup.list.bash", { link = "@punctuation.bash" })
hi(0, "@markup.list.checked", { fg = "#116329" })
hi(0, "@markup.list.luadoc", { fg = "#1f2328" })
hi(0, "@markup.list.unchecked", { fg = "#57606a" })
hi(0, "@markup.quote.markdown", { fg = "#116329" })
hi(0, "@markup.raw", { fg = "#1f2328", italic = true })
hi(0, "@markup.strikethrough", { fg = "#1f2328", strikethrough = true })
hi(0, "@markup.strong", { bold = true, fg = "#1f2328" })
hi(0, "@module", { fg = "#cf222e" })
hi(0, "@module.builtin", { fg = "#0550ae" })
hi(0, "@module.builtin.lua", { fg = "#0550ae" })
hi(0, "@module.c_sharp", { fg = "#953800" })
hi(0, "@module.elixir", { link = "@type" })
hi(0, "@module.go", {})
hi(0, "@module.php", { link = "@constructor.php" })
hi(0, "@module.python", {})
hi(0, "@module.rust", {})
hi(0, "@none", { link = "NONE" })
hi(0, "@number.bash", {})
hi(0, "@operator.bash", { fg = "#cf222e" })
hi(0, "@operator.lua", { fg = "#cf222e" })
hi(0, "@operator.luadoc", { fg = "#1f2328" })
hi(0, "@property", { link = "@variable.member" })
hi(0, "@property.json", { link = "@tag" })
hi(0, "@property.lua", { fg = "#1f2328" })
hi(0, "@property.luadoc", { link = "@property.lua" })
hi(0, "@property.scss", { link = "@constant" })
hi(0, "@property.yaml", { link = "@tag" })
hi(0, "@punctuation.bracket", { fg = "#1f2328" })
hi(0, "@punctuation.delimiter.bash", { fg = "#cf222e" })
hi(0, "@punctuation.delimiter.markdown", { fg = "#1f2328" })
hi(0, "@punctuation.delimiter.markdown_inline", { fg = "#1f2328" })
hi(0, "@string.escape", { bold = true, fg = "#0a3069" })
hi(0, "@string.regexp", { fg = "#0a3069" })
hi(0, "@string.special.path.gitignore", { fg = "#6639ba" })
hi(0, "@string.special.path.nix", { link = "@string" })
hi(0, "@string.special.symbol", { link = "@constant" })
hi(0, "@string.special.symbol.make", { link = "@function" })
hi(0, "@string.special.symbol.ruby", { link = "@constant" })
hi(0, "@string.special.url", { fg = "#0550ae", italic = true, underline = true })
hi(0, "@tag", { fg = "#116329" })
hi(0, "@tag.attribute", { link = "@variable.member" })
hi(0, "@tag.builtin", { link = "@tag" })
hi(0, "@tag.delimiter", {})
hi(0, "@tag.delimiter.javascript", { link = "@tag.attribute.javascript" })
hi(0, "@tag.delimiter.tsx", { link = "@tag.attribute.tsx" })
hi(0, "@tag.javascript", { link = "@type.javascript" })
hi(0, "@tag.tsx", { link = "@type.tsx" })
hi(0, "@type", { fg = "#953800" })
hi(0, "@type.builtin", { fg = "#cf222e" })
hi(0, "@type.builtin.python", { link = "@constant" })
hi(0, "@type.c", {})
hi(0, "@type.css", { link = "htmlTag" })
hi(0, "@type.qualifier", { fg = "#cf222e" })
hi(0, "@type.sql", { link = "@variable" })
hi(0, "@variable", { fg = "#1f2328" })
hi(0, "@variable.builtin", { fg = "#0550ae" })
hi(0, "@variable.builtin.python", { link = "@constant" })
hi(0, "@variable.member", { fg = "#0550ae" })
hi(0, "@variable.member.luadoc", { link = "@property.luadoc" })
hi(0, "@variable.member.nix", { link = "@variable.member" })
hi(0, "@variable.member.python", { fg = "#1f2328" })
hi(0, "@variable.member.sql", { link = "@constant" })
hi(0, "@variable.parameter", { fg = "#1f2328" })
hi(0, "@variable.parameter.builtin", { fg = "#0550ae" })
hi(0, "@variable.parameter.nix", { link = "@variable.parameter" })
hi(0, "@variable.parameter.vimdoc", { fg = "#953800" })
hi(0, "@variable.scss", { link = "@variable.parameter" })
hi(0, "@variable.sql", { link = "@constant" })
hi(0, "Added", { bg = "#b8d0bf", fg = "#1a7f37" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { link = "Number" })
hi(0, "Changed", { bg = "#d8cab3", fg = "#9a6700" })
hi(0, "Character", { link = "String" })
hi(0, "CmpDocumentation", { bg = "#f6f8fa", fg = "#1f2328" })
hi(0, "CmpDocumentationBorder", { bg = "#f6f8fa", fg = "#dae9f9" })
hi(0, "CmpItemAbbr", { fg = "#1f2328" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#82071e", strikethrough = true })
hi(0, "CmpItemAbbrMatch", { fg = "#6639ba" })
hi(0, "CmpItemAbbrMatchFuzzy", { fg = "#6639ba" })
hi(0, "CmpItemKindClass", { link = "Type" })
hi(0, "CmpItemKindConstant", { link = "@constant" })
hi(0, "CmpItemKindConstructor", { link = "@constructor" })
hi(0, "CmpItemKindDefault", { fg = "#32383f" })
hi(0, "CmpItemKindEnum", { link = "Constant" })
hi(0, "CmpItemKindEnumMember", { link = "@variable.member" })
hi(0, "CmpItemKindEvent", { link = "Constant" })
hi(0, "CmpItemKindField", { link = "@variable.member" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindInterface", { link = "Constant" })
hi(0, "CmpItemKindKeyword", { link = "Keyword" })
hi(0, "CmpItemKindMethod", { link = "Function" })
hi(0, "CmpItemKindModule", { link = "@module" })
hi(0, "CmpItemKindOperator", { link = "Operator" })
hi(0, "CmpItemKindProperty", { link = "@property" })
hi(0, "CmpItemKindReference", { link = "Keyword" })
hi(0, "CmpItemKindSnippet", { fg = "#32383f" })
hi(0, "CmpItemKindStruct", { link = "Type" })
hi(0, "CmpItemKindTypeParameter", { link = "@variable.member" })
hi(0, "CmpItemKindUnit", { link = "Constant" })
hi(0, "CmpItemKindValue", { link = "Keyword" })
hi(0, "CmpItemKindVariable", { link = "@variable" })
hi(0, "CmpItemMenu", { link = "Comment" })
hi(0, "CocExplorerFileDirectory", { bold = true, fg = "#1f2328" })
hi(0, "CocExplorerFileRootName", { bold = true, fg = "#1f2328" })
hi(0, "CocExplorerGitAdded", { fg = "#1a7f37" })
hi(0, "CocExplorerGitContentChange", { fg = "#9a6700" })
hi(0, "CocExplorerGitIgnored", { fg = "#57606a" })
hi(0, "CocExplorerGitModified", { fg = "#9a6700" })
hi(0, "CocExplorerGitPathChange", { fg = "#8250df" })
hi(0, "CocExplorerGitPathChange_Internal", { fg = "#8250df" })
hi(0, "CocExplorerGitUntracked", { fg = "#57606a" })
hi(0, "CocExplorerNormalFloat", { link = "NormalSB" })
hi(0, "CocInlayHint", { bg = "#f1f1f2", fg = "#57606a" })
hi(0, "ColorColumn", { bg = "#f1f1f2" })
hi(0, "Comment", { fg = "#57606a", nocombine = true })
hi(0, "Conceal", { fg = "#6e7781" })
hi(0, "Conditional", { fg = "#cf222e" })
hi(0, "Constant", { fg = "#0550ae" })
hi(0, "CopilotSuggestion", { ctermfg = 244, fg = "#808080" })
hi(0, "CurSearch", { link = "IncSearch" })
hi(0, "Cursor", { bg = "#1f2328", fg = "#ffffff" })
hi(0, "CursorColumn", { link = "CursorLine" })
hi(0, "CursorLine", { bg = "#e7eaf0" })
hi(0, "CursorLineNr", { fg = "#1f2328" })
hi(0, "DapUIBreakpointsCurrentLine", { link = "DapUIThread" })
hi(0, "DapUIBreakpointsDisabledLine", { fg = "#6e7781" })
hi(0, "DapUIBreakpointsInfo", { link = "DapUIWatchesValue" })
hi(0, "DapUIBreakpointsPath", { link = "DapUIScope" })
hi(0, "DapUIDecoration", { link = "DapUIScope" })
hi(0, "DapUIFloatBorder", { link = "DapUIScope" })
hi(0, "DapUILineNumber", { link = "DapUIScope" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#1b7c83" })
hi(0, "DapUIPlayPause", { link = "DapUIWatchesValue" })
hi(0, "DapUIRestart", { link = "DapUIWatchesValue" })
hi(0, "DapUIScope", { fg = "#1b7c83" })
hi(0, "DapUISource", { link = "DapUIType" })
hi(0, "DapUIStepBack", { link = "DapUIScope" })
hi(0, "DapUIStepInto", { link = "DapUIScope" })
hi(0, "DapUIStepOut", { link = "DapUIScope" })
hi(0, "DapUIStepOver", { link = "DapUIScope" })
hi(0, "DapUIStop", { link = "DapUIWatchesEmpty" })
hi(0, "DapUIStoppedThread", { link = "DapUIScope" })
hi(0, "DapUIThread", { bold = true, fg = "#116329" })
hi(0, "DapUIType", { fg = "#8250df" })
hi(0, "DapUIUnavailable", { link = "DapUIBreakpointsDisabledLine" })
hi(0, "DapUIWatchesEmpty", { fg = "#cf222e" })
hi(0, "DapUIWatchesError", { link = "DapUIWatchesEmpty" })
hi(0, "DapUIWatchesValue", { fg = "#116329" })
hi(0, "DapUIWinSelect", { link = "DapUIModifiedValue" })
hi(0, "DashboardCenter", { link = "String" })
hi(0, "DashboardFooter", { fg = "#0550ae", italic = true })
hi(0, "DashboardHeader", { link = "Title" })
hi(0, "DashboardShortCut", { link = "Identifier" })
hi(0, "Delimiter", { link = "Special" })
hi(0, "DiagnosticError", { fg = "#d1242f" })
hi(0, "DiagnosticHint", { fg = "#d0d7de" })
hi(0, "DiagnosticInfo", { fg = "#0969da" })
hi(0, "DiagnosticUnderlineError", { sp = "#d1242f", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#d0d7de", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#0969da", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#9a6700", undercurl = true })
hi(0, "DiagnosticVirtualTextError", { fg = "#d1242f" })
hi(0, "DiagnosticVirtualTextHint", { fg = "#d0d7de" })
hi(0, "DiagnosticVirtualTextInfo", { fg = "#0969da" })
hi(0, "DiagnosticVirtualTextWarn", { fg = "#9a6700" })
hi(0, "DiagnosticWarn", { fg = "#9a6700" })
hi(0, "DiffAdd", { link = "diffAdded" })
hi(0, "DiffChange", { link = "diffChanged" })
hi(0, "DiffDelete", { link = "diffRemoved" })
hi(0, "DiffText", { bg = "#f1f1f2", fg = "#1f2328" })
hi(0, "Directory", { fg = "#6639ba" })
hi(0, "EndOfBuffer", { fg = "#ffffff" })
hi(0, "Error", { fg = "#d1242f" })
hi(0, "ErrorMsg", { fg = "#d1242f" })
hi(0, "Exception", { link = "Keyword" })
hi(0, "FidgetTask", { link = "LineNr" })
hi(0, "FidgetTitle", { link = "Title" })
hi(0, "FloatBorder", { fg = "#d0d7de" })
hi(0, "FoldColumn", { fg = "#57606a" })
hi(0, "Folded", { bg = "#f1f1f2", fg = "#57606a" })
hi(0, "Function", { fg = "#6639ba" })
hi(0, "FzfLuaBorder", { link = "Normal" })
hi(0, "FzfLuaCursor", { link = "Cursor" })
hi(0, "FzfLuaCursorLine", { link = "CursorLine" })
hi(0, "FzfLuaCursorLineNr", { link = "CursorLineNr" })
hi(0, "FzfLuaHelpBorder", { link = "FzfLuaBorder" })
hi(0, "FzfLuaHelpNormal", { link = "FzfLuaNormal" })
hi(0, "FzfLuaNormal", { link = "Normal" })
hi(0, "FzfLuaScrollBorderEmpty", { link = "FzfLuaBorder" })
hi(0, "FzfLuaScrollBorderFull", { link = "FzfLuaBorder" })
hi(0, "FzfLuaScrollFloatEmpty", { link = "PmenuSbar" })
hi(0, "FzfLuaScrollFloatFull", { link = "PmenuThumb" })
hi(0, "FzfLuaSearch", { link = "IncSearch" })
hi(0, "FzfLuaTitle", { link = "Title" })
hi(0, "GitGutterAdd", { fg = "#1a7f37" })
hi(0, "GitGutterChange", { fg = "#9a6700" })
hi(0, "GitGutterDelete", { fg = "#d1242f" })
hi(0, "GitSignsAdd", { fg = "#1a7f37" })
hi(0, "GitSignsChange", { fg = "#9a6700" })
hi(0, "GitSignsDelete", { fg = "#d1242f" })
hi(0, "Identifier", { fg = "#1f2328" })
hi(0, "IncSearch", { bg = "#fb8f44", fg = "#57606a" })
hi(0, "IndentBlanklineChar", { fg = "#e9e9ea" })
hi(0, "IndentBlanklineContextChar", { fg = "#b7d9e1" })
hi(0, "IndentBlanklineContextStart", { sp = "#fb8f44", underline = true })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#cf222e" })
hi(0, "Label", { link = "Conditional" })
hi(0, "LineNr", { fg = "#6e7781" })
hi(0, "LspCodeLens", { fg = "#57606a" })
hi(0, "LspCodeLensSeparator", { fg = "#57606a" })
hi(0, "LspInlayHint", { bg = "#f1f1f2", fg = "#57606a" })
hi(0, "LspReferenceRead", { bg = "#dae9f9" })
hi(0, "LspReferenceText", { bg = "#dae9f9" })
hi(0, "LspReferenceWrite", { bg = "#dae9f9" })
hi(0, "LspSignatureActiveParameter", { fg = "#c2e2ff" })
hi(0, "LspTroubleCount", { bg = "#57606a", fg = "#8250df" })
hi(0, "LspTroubleNormal", { bg = "#f6f8fa", fg = "#57606a" })
hi(0, "LspTroubleText", { fg = "#32383f" })
hi(0, "MatchParen", { bg = "#bbdfff", bold = true, fg = "#1f2328" })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hi(0, "MiniClueBorder", { link = "FloatBorder" })
hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
hi(0, "MiniClueNextKey", { fg = "#0969da" })
hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hi(0, "MiniClueSeparator", { fg = "#d0d7de" })
hi(0, "MiniClueTitle", { link = "FloatTitle" })
hi(0, "MiniCompletionActiveParameter", { underline = true })
hi(0, "MiniCursorword", { bg = "#dae9f9" })
hi(0, "MiniCursorwordCurrent", { bg = "#dae9f9" })
hi(0, "MiniDepsChangeAdded", { link = "diffAdded" })
hi(0, "MiniDepsChangeRemoved", { link = "diffRemoved" })
hi(0, "MiniDiffOverChange", { bg = "#e7eaf0", fg = "#1f2328" })
hi(0, "MiniDiffSignAdd", { fg = "#1a7f37" })
hi(0, "MiniDiffSignChange", { fg = "#9a6700" })
hi(0, "MiniDiffSignDelete", { fg = "#d1242f" })
hi(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniFilesFile", { fg = "#1f2328" })
hi(0, "MiniFilesTitleFocused", { bold = true, fg = "#1f2328" })
hi(0, "MiniHipatternsFixme", { bg = "#d1242f", bold = true, fg = "#f6f8fa" })
hi(0, "MiniHipatternsHack", { bg = "#9a6700", bold = true, fg = "#f6f8fa" })
hi(0, "MiniHipatternsNote", { bg = "#0969da", bold = true, fg = "#f6f8fa" })
hi(0, "MiniHipatternsTodo", { bg = "#d0d7de", bold = true, fg = "#f6f8fa" })
hi(0, "MiniIconsAzure", { fg = "#218bff" })
hi(0, "MiniIconsBlue", { fg = "#0969da" })
hi(0, "MiniIconsCyan", { fg = "#1b7c83" })
hi(0, "MiniIconsGreen", { fg = "#1a7f37" })
hi(0, "MiniIconsGrey", { fg = "#1f2328" })
hi(0, "MiniIconsOrange", { fg = "#fb8f44" })
hi(0, "MiniIconsPurple", { fg = "#8250df" })
hi(0, "MiniIconsRed", { fg = "#cf222e" })
hi(0, "MiniIconsYellow", { fg = "#633c01" })
hi(0, "MiniIndentscopePrefix", { nocombine = true })
hi(0, "MiniIndentscopeSymbol", { link = "Delimiter" })
hi(0, "MiniJump", { link = "SpellRare" })
hi(0, "MiniJump2dDim", { link = "Comment" })
hi(0, "MiniJump2dSpot", { bold = true, fg = "#a40e26" })
hi(0, "MiniJump2dSpotAhead", { fg = "#0969da", nocombine = true })
hi(0, "MiniJump2dSpotUnique", { bold = true, fg = "#9a6700" })
hi(0, "MiniMapNormal", { link = "NormalFloat" })
hi(0, "MiniMapSymbolCount", { link = "Special" })
hi(0, "MiniMapSymbolLine", { fg = "#0969da" })
hi(0, "MiniMapSymbolView", { fg = "#bbdfff" })
hi(0, "MiniNotifyBorder", { link = "FloatBorder" })
hi(0, "MiniNotifyNormal", { link = "NormalFloat" })
hi(0, "MiniPickCursor", { blend = 100, nocombine = true })
hi(0, "MiniPickHeader", { fg = "#0550ae" })
hi(0, "MiniPickMatchRanges", { fg = "#9a6700" })
hi(0, "MiniPickNormal", { link = "NormalFloat" })
hi(0, "MiniPickPrompt", { fg = "#0550ae" })
hi(0, "MiniSnippetsCurrent", { sp = "#9a6700", underdouble = true })
hi(0, "MiniSnippetsCurrentReplace", { sp = "#d1242f", underdouble = true })
hi(0, "MiniSnippetsFinal", { sp = "#005523", underdouble = true })
hi(0, "MiniSnippetsUnvisited", { sp = "#d0d7de", underdouble = true })
hi(0, "MiniSnippetsVisited", { sp = "#0969da", underdouble = true })
hi(0, "MiniStarterCurrent", { nocombine = true })
hi(0, "MiniStarterFooter", { fg = "#6e7781", italic = true })
hi(0, "MiniStarterHeader", { fg = "#0969da" })
hi(0, "MiniStarterInactive", { link = "Comment" })
hi(0, "MiniStarterItem", { link = "Normal" })
hi(0, "MiniStarterItemBullet", { fg = "#d0d7de" })
hi(0, "MiniStarterItemPrefix", { fg = "#9a6700" })
hi(0, "MiniStarterQuery", { fg = "#0969da" })
hi(0, "MiniStarterSection", { link = "Special" })
hi(0, "MiniStatuslineDevinfo", { bg = "#e7eaf0", fg = "#1f2328" })
hi(0, "MiniStatuslineFileinfo", { bg = "#e7eaf0", fg = "#1f2328" })
hi(0, "MiniStatuslineFilename", { bg = "#ffffff", fg = "#8f9193" })
hi(0, "MiniStatuslineInactive", { bg = "#f6f8fa", fg = "#8f9193" })
hi(0, "MiniStatuslineModeCommand", { bg = "#a475f9", bold = true, fg = "#ffffff" })
hi(0, "MiniStatuslineModeInsert", { bg = "#116329", bold = true, fg = "#ffffff" })
hi(0, "MiniStatuslineModeNormal", { bg = "#0969da", bold = true, fg = "#ffffff" })
hi(0, "MiniStatuslineModeOther", { bold = true, fg = "#ffffff" })
hi(0, "MiniStatuslineModeReplace", { bg = "#cf222e", bold = true, fg = "#ffffff" })
hi(0, "MiniStatuslineModeVisual", { bg = "#4d2d00", bold = true, fg = "#ffffff" })
hi(0, "MiniTablineCurrent", { bg = "#59a8ff", bold = true, fg = "#f6f8fa" })
hi(0, "MiniTablineFill", { link = "TabLineFill" })
hi(0, "MiniTablineHidden", { bg = "#ffffff", fg = "#1f2328" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#f6f8fa", bold = true, fg = "#59a8ff" })
hi(0, "MiniTablineModifiedHidden", { bg = "#1f2328", fg = "#ffffff" })
hi(0, "MiniTablineModifiedVisible", { bg = "#f6f8fa", fg = "#90c5ff" })
hi(0, "MiniTablineTabpagesection", { bg = "#c2e2ff", bold = true })
hi(0, "MiniTablineVisible", { bg = "#90c5ff", fg = "#f6f8fa" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#cf222e" })
hi(0, "MiniTestPass", { bold = true, fg = "#116329" })
hi(0, "MiniTrailspace", { bg = "#cf222e" })
hi(0, "ModeMsg", { bold = true, fg = "#9a6700" })
hi(0, "MoreMsg", { bold = true, fg = "#0969da" })
hi(0, "NeoTreeDimText", { link = "Conceal" })
hi(0, "NeoTreeDirectoryIcon", { fg = "#1f2328" })
hi(0, "NeoTreeDirectoryName", { fg = "#1f2328" })
hi(0, "NeoTreeDotfile", { fg = "#84b4ed" })
hi(0, "NeoTreeEndOfBuffer", { fg = "#f6f8fa" })
hi(0, "NeoTreeFileName", { fg = "#1f2328" })
hi(0, "NeoTreeFileNameOpened", { fg = "#218bff" })
hi(0, "NeoTreeGitAdded", { fg = "#1a7f37" })
hi(0, "NeoTreeGitConflict", { fg = "#bc4c00", italic = true })
hi(0, "NeoTreeGitDeleted", { fg = "#d1242f" })
hi(0, "NeoTreeGitIgnored", { fg = "#6e7781" })
hi(0, "NeoTreeGitModified", { fg = "#9a6700" })
hi(0, "NeoTreeGitUntracked", { fg = "#32898f" })
hi(0, "NeoTreeIndentMarker", { fg = "#6e7781" })
hi(0, "NeoTreeNormal", { link = "NormalSB" })
hi(0, "NeoTreeNormalNC", { link = "NeoTreeNormal" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#1f2328" })
hi(0, "NeoTreeSymbolicLinkTarget", { fg = "#df9cc4" })
hi(0, "NeoTreeTitleBar", { bg = "#2278de", fg = "#ffffff" })
hi(0, "NeogitBranch", { fg = "#9a6700" })
hi(0, "NeogitDiffAdd", { fg = "#1a7f37" })
hi(0, "NeogitDiffAddHighlight", { bg = "#b8d0bf" })
hi(0, "NeogitDiffContextHighlight", { bg = "#f1f1f2" })
hi(0, "NeogitDiffDelete", { fg = "#d1242f" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#e4b7be" })
hi(0, "NeogitHunkHeader", { bg = "#e7eaf0", fg = "#0969da" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#dae9f9", fg = "#0969da" })
hi(0, "NeogitNotificationError", { fg = "#d1242f" })
hi(0, "NeogitNotificationInfo", { fg = "#0969da" })
hi(0, "NeogitNotificationWarning", { fg = "#9a6700" })
hi(0, "NeogitRemote", { fg = "#d0d7de" })
hi(0, "NonText", { fg = "#6e7781" })
hi(0, "Normal", { bg = "#ffffff", fg = "#1f2328" })
hi(0, "NormalFloat", { bg = "#f6f8fa", fg = "#1f2328" })
hi(0, "NormalNC", { bg = "#ffffff", fg = "#1f2328" })
hi(0, "NormalSB", { bg = "#f6f8fa", fg = "#1f2328" })
hi(0, "NotifyDEBUGBody", { link = "NotifyDEBUGTitle" })
hi(0, "NotifyDEBUGBorder", { link = "NotifyDEBUGTitle" })
hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGTitle" })
hi(0, "NotifyDEBUGTitle", { fg = "#1f2328" })
hi(0, "NotifyERRORBody", { link = "NotifyERRORTitle" })
hi(0, "NotifyERRORBorder", { link = "NotifyERRORTitle" })
hi(0, "NotifyERRORIcon", { link = "NotifyERRORTitle" })
hi(0, "NotifyERRORTitle", { fg = "#cf222e" })
hi(0, "NotifyINFOBody", { link = "NotifyINFOTitle" })
hi(0, "NotifyINFOBorder", { link = "NotifyINFOTitle" })
hi(0, "NotifyINFOIcon", { link = "NotifyINFOTitle" })
hi(0, "NotifyINFOTitle", { fg = "#116329" })
hi(0, "NotifyTRACEBody", { link = "NotifyTRACETitle" })
hi(0, "NotifyTRACEBorder", { link = "NotifyTRACETitle" })
hi(0, "NotifyTRACEIcon", { link = "NotifyTRACETitle" })
hi(0, "NotifyTRACETitle", { fg = "#a475f9" })
hi(0, "NotifyWARNBody", { link = "NotifyWARNTitle" })
hi(0, "NotifyWARNBorder", { link = "NotifyWARNTitle" })
hi(0, "NotifyWARNIcon", { link = "NotifyWARNTitle" })
hi(0, "NotifyWARNTitle", { fg = "#4d2d00" })
hi(0, "Number", { fg = "#0550ae" })
hi(0, "NvimTreeEndOfBuffer", { fg = "#f6f8fa" })
hi(0, "NvimTreeFolderName", { fg = "#1f2328" })
hi(0, "NvimTreeGitDeleted", { fg = "#d1242f" })
hi(0, "NvimTreeGitDirty", { fg = "#9a6700" })
hi(0, "NvimTreeGitIgnored", { fg = "#57606a" })
hi(0, "NvimTreeGitNew", { fg = "#1a7f37" })
hi(0, "NvimTreeGitRenamed", { fg = "#8250df" })
hi(0, "NvimTreeImageFile", { fg = "#633c01" })
hi(0, "NvimTreeIndentMarker", { fg = "#57606a" })
hi(0, "NvimTreeNormal", { link = "NormalSB" })
hi(0, "NvimTreeOpenedFile", { fg = "#218bff" })
hi(0, "NvimTreeOpenedFolderName", { bold = true, fg = "#1f2328" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#1f2328" })
hi(0, "NvimTreeSpecialFile", { fg = "#4d2d00", underline = true })
hi(0, "NvimTreeSymlink", { fg = "#8250df" })
hi(0, "Operator", { fg = "#0550ae" })
hi(0, "Pmenu", { bg = "#f6f8fa", fg = "#1f2328" })
hi(0, "PmenuSel", { bg = "#c2e2ff" })
hi(0, "PmenuThumb", { bg = "#dae9f9" })
hi(0, "PreProc", { fg = "#cf222e" })
hi(0, "Question", { link = "MoreMsg" })
hi(0, "QuickFixLine", { link = "CursorLine" })
hi(0, "Removed", { bg = "#e4b7be", fg = "#d1242f" })
hi(0, "Repeat", { link = "Conditional" })
hi(0, "Search", { bg = "#e1d1b3" })
hi(0, "SignColumn", { fg = "#57606a" })
hi(0, "SignColumnSB", { link = "SignColumn" })
hi(0, "Special", { fg = "#1f2328" })
hi(0, "SpecialKey", { link = "NonText" })
hi(0, "SpellBad", { sp = "#d1242f", undercurl = true })
hi(0, "SpellCap", { sp = "#9a6700", undercurl = true })
hi(0, "SpellLocal", { sp = "#0969da", undercurl = true })
hi(0, "SpellRare", { sp = "#0969da", undercurl = true })
hi(0, "Statement", { fg = "#cf222e" })
hi(0, "StatusLine", { bg = "#5094e4", fg = "#f6f8fa" })
hi(0, "StatusLineNC", { bg = "#ffffff", fg = "#ffffff", sp = "#f6f8fa", underline = true })
hi(0, "String", { fg = "#0a3069" })
hi(0, "Substitute", { bg = "#d1242f", fg = "#ffffff" })
hi(0, "TabLine", { bg = "#f1f1f2", fg = "#32383f" })
hi(0, "TabLineFill", { bg = "#f6f8fa" })
hi(0, "TabLineSel", { bg = "#57606a", fg = "#ffffff" })
hi(0, "TelescopeMatching", { link = "Search" })
hi(0, "TelescopeSelection", { link = "CursorLine" })
hi(0, "TelescopeSelectionCaret", { fg = "#0969da" })
hi(0, "Title", { bold = true, fg = "#0550ae" })
hi(0, "Todo", { bg = "#0969da", fg = "#ffffff" })
hi(0, "TreesitterContext", { bg = "#ddf4ff" })
hi(0, "Type", { fg = "#953800" })
hi(0, "VertSplit", { fg = "#d0d7de" })
hi(0, "Visual", { bg = "#dae9f9" })
hi(0, "WarningMsg", { fg = "#9a6700" })
hi(0, "WhichKey", { link = "Identifier" })
hi(0, "WhichKeyDesc", { link = "Keyword" })
hi(0, "WhichKeyFloat", { bg = "#f6f8fa" })
hi(0, "WhichKeyGroup", { link = "Function" })
hi(0, "WhichKeySeparator", { link = "Comment" })
hi(0, "WhichKeySeperator", { link = "Comment" })
hi(0, "WhichKeyValue", { link = "Comment" })
hi(0, "Whitespace", { fg = "#e7eaf0" })
hi(0, "WildMenu", { link = "Pmenu" })
hi(0, "WinBar", { bg = "#ffffff", bold = true, fg = "#57606a" })
hi(0, "WinBarNC", { bg = "#ffffff", bold = true, fg = "#57606a" })
hi(0, "WinSeparator", { fg = "#d0d7de" })
hi(0, "cssBraces", { fg = "#1f2328" })
hi(0, "cssMedia", { link = "Keyword" })
hi(0, "cssProp", { link = "Constant" })
hi(0, "cssPseudoClassId", { link = "Function" })
hi(0, "diffAdded", { link = "Added" })
hi(0, "diffChanged", { link = "Changed" })
hi(0, "diffFile", { fg = "#0969da" })
hi(0, "diffIndexLine", { fg = "#cf222e" })
hi(0, "diffLine", { fg = "#0550ae" })
hi(0, "diffNewFile", { fg = "#d0d7de" })
hi(0, "diffOldFile", { fg = "#9a6700" })
hi(0, "diffRemoved", { link = "Removed" })
hi(0, "htmlTag", { fg = "#116329" })
hi(0, "jsonKeyword", { fg = "#116329" })
hi(0, "jsonNull", { link = "Constant" })
hi(0, "lCursor", { link = "Cursor" })
hi(0, "lessAmpersand", { link = "Function" })
hi(0, "lessClass", { link = "Function" })
hi(0, "lessClassCall", { link = "Function" })
hi(0, "lessCssAttribute", { link = "Constant" })
hi(0, "lessFunction", { link = "Constant" })
hi(0, "lessVariable", { fg = "#1f2328" })
hi(0, "luaFunction", { link = "Keyword" })
hi(0, "qfFileName", { link = "Directory" })
hi(0, "qfLineNr", { link = "LineNr" })
hi(0, "xmlAttrib", { link = "htmlTag" })
hi(0, "xmlTagName", { link = "htmlTag" })
hi(0, "yamlBlockMappingKey", { fg = "#116329" })
hi(0, "yamlFlowMappingKey", { fg = "#116329" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#24292f"
g.terminal_color_1 = "#cf222e"
g.terminal_color_2 = "#116329"
g.terminal_color_3 = "#4d2d00"
g.terminal_color_4 = "#0969da"
g.terminal_color_5 = "#8250df"
g.terminal_color_6 = "#1b7c83"
g.terminal_color_7 = "#6e7781"
g.terminal_color_8 = "#57606a"
g.terminal_color_9 = "#a40e26"
g.terminal_color_10 = "#1a7f37"
g.terminal_color_11 = "#633c01"
g.terminal_color_12 = "#218bff"
g.terminal_color_13 = "#a475f9"
g.terminal_color_14 = "#3192aa"
g.terminal_color_15 = "#8c959f"
