if vim.g.colors_name ~= nil then
	vim.cmd("highlight clear")
end
vim.g.colors_name = "tokyonight-storm"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@annotation", { link = "PreProc" })
hi(0, "@attribute", { link = "PreProc" })
hi(0, "@character.printf", { link = "SpecialChar" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.error", { fg = "#db4b4b" })
hi(0, "@comment.hint", { fg = "#1abc9c" })
hi(0, "@comment.info", { fg = "#0db9d7" })
hi(0, "@comment.note", { fg = "#1abc9c" })
hi(0, "@comment.todo", { fg = "#7aa2f7" })
hi(0, "@comment.warning", { fg = "#e0af68" })
hi(0, "@constant.builtin", { link = "Special" })
hi(0, "@constant.macro", { link = "Define" })
hi(0, "@constructor", { fg = "#bb9af7" })
hi(0, "@constructor.tsx", { fg = "#2ac3de" })
hi(0, "@diff.delta", { link = "DiffChange" })
hi(0, "@diff.minus", { link = "DiffDelete" })
hi(0, "@diff.plus", { link = "DiffAdd" })
hi(0, "@function.builtin", { link = "Special" })
hi(0, "@function.call", { link = "@function" })
hi(0, "@function.macro", { link = "Macro" })
hi(0, "@function.method", { link = "Function" })
hi(0, "@function.method.call", { link = "@function.method" })
hi(0, "@keyword", { fg = "#9d7cd8", italic = true })
hi(0, "@keyword.conditional", { link = "Conditional" })
hi(0, "@keyword.coroutine", { link = "@keyword" })
hi(0, "@keyword.debug", { link = "Debug" })
hi(0, "@keyword.directive", { link = "PreProc" })
hi(0, "@keyword.directive.define", { link = "Define" })
hi(0, "@keyword.exception", { link = "Exception" })
hi(0, "@keyword.function", { fg = "#bb9af7" })
hi(0, "@keyword.import", { link = "Include" })
hi(0, "@keyword.operator", { link = "@operator" })
hi(0, "@keyword.repeat", { link = "Repeat" })
hi(0, "@keyword.return", { link = "@keyword" })
hi(0, "@keyword.storage", { link = "StorageClass" })
hi(0, "@label", { fg = "#7aa2f7" })
hi(0, "@lsp.type.boolean", { link = "@boolean" })
hi(0, "@lsp.type.builtinType", { link = "@type.builtin" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.deriveHelper", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.escapeSequence", { link = "@string.escape" })
hi(0, "@lsp.type.formatSpecifier", { link = "@markup.list" })
hi(0, "@lsp.type.generic", { link = "@variable" })
hi(0, "@lsp.type.interface", { fg = "#57c5e5" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.lifetime", { link = "@keyword.storage" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.namespace.python", { link = "@variable" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.selfKeyword", { link = "@variable.builtin" })
hi(0, "@lsp.type.selfTypeKeyword", { link = "@variable.builtin" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.typeAlias", { link = "@type.definition" })
hi(0, "@lsp.type.unresolvedReference", { sp = "#db4b4b", undercurl = true })
hi(0, "@lsp.type.variable", vim.empty_dict())
hi(0, "@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.keyword.async", { link = "@keyword.coroutine" })
hi(0, "@lsp.typemod.keyword.injected", { link = "@keyword" })
hi(0, "@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.struct.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.type.defaultLibrary", { fg = "#29a4bd" })
hi(0, "@lsp.typemod.typeAlias.defaultLibrary", { fg = "#29a4bd" })
hi(0, "@lsp.typemod.variable.callable", { link = "@function" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@lsp.typemod.variable.static", { link = "@constant" })
hi(0, "@markup", { link = "@none" })
hi(0, "@markup.emphasis", { italic = true })
hi(0, "@markup.environment", { link = "Macro" })
hi(0, "@markup.environment.name", { link = "Type" })
hi(0, "@markup.heading", { link = "Title" })
hi(
	0,
	"@markup.heading.1.delimiter.vimdoc",
	{ bg = "#24283b", fg = "#24283b", nocombine = true, sp = "#c0caf5", underdouble = true }
)
hi(0, "@markup.heading.1.markdown", { bold = true, fg = "#7aa2f7" })
hi(
	0,
	"@markup.heading.2.delimiter.vimdoc",
	{ bg = "#24283b", fg = "#24283b", nocombine = true, sp = "#c0caf5", underline = true }
)
hi(0, "@markup.heading.2.markdown", { bold = true, fg = "#e0af68" })
hi(0, "@markup.heading.3.markdown", { bold = true, fg = "#9ece6a" })
hi(0, "@markup.heading.4.markdown", { bold = true, fg = "#1abc9c" })
hi(0, "@markup.heading.5.markdown", { bold = true, fg = "#bb9af7" })
hi(0, "@markup.heading.6.markdown", { bold = true, fg = "#9d7cd8" })
hi(0, "@markup.heading.7.markdown", { bold = true, fg = "#ff9e64" })
hi(0, "@markup.heading.8.markdown", { bold = true, fg = "#f7768e" })
hi(0, "@markup.link", { fg = "#1abc9c" })
hi(0, "@markup.link.label", { link = "SpecialChar" })
hi(0, "@markup.link.label.symbol", { link = "Identifier" })
hi(0, "@markup.link.url", { link = "Underlined" })
hi(0, "@markup.list", { fg = "#89ddff" })
hi(0, "@markup.list.checked", { fg = "#73daca" })
hi(0, "@markup.list.markdown", { bold = true, fg = "#ff9e64" })
hi(0, "@markup.list.unchecked", { fg = "#7aa2f7" })
hi(0, "@markup.math", { link = "Special" })
hi(0, "@markup.raw", { link = "String" })
hi(0, "@markup.raw.markdown_inline", { bg = "#414868", fg = "#7aa2f7" })
hi(0, "@module", { link = "Directory" })
hi(0, "@module.builtin", { fg = "#f7768e" })
hi(0, "@namespace.builtin", { link = "@variable.builtin" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@operator", { fg = "#89ddff" })
hi(0, "@property", { fg = "#73daca" })
hi(0, "@punctuation.bracket", { fg = "#a9b1d6" })
hi(0, "@punctuation.delimiter", { fg = "#89ddff" })
hi(0, "@punctuation.special", { fg = "#89ddff" })
hi(0, "@punctuation.special.markdown", { fg = "#ff9e64" })
hi(0, "@string.documentation", { fg = "#e0af68" })
hi(0, "@string.escape", { fg = "#bb9af7" })
hi(0, "@string.regexp", { fg = "#b4f9f8" })
hi(0, "@tag", { link = "Label" })
hi(0, "@tag.attribute", { link = "@property" })
hi(0, "@tag.delimiter", { link = "Delimiter" })
hi(0, "@tag.delimiter.tsx", { fg = "#607dbf" })
hi(0, "@tag.javascript", { fg = "#f7768e" })
hi(0, "@tag.tsx", { fg = "#f7768e" })
hi(0, "@type.builtin", { fg = "#29a4bd" })
hi(0, "@type.definition", { link = "Typedef" })
hi(0, "@type.qualifier", { link = "@keyword" })
hi(0, "@variable", { fg = "#c0caf5" })
hi(0, "@variable.builtin", { fg = "#f7768e" })
hi(0, "@variable.member", { fg = "#73daca" })
hi(0, "@variable.parameter", { fg = "#e0af68" })
hi(0, "@variable.parameter.builtin", { fg = "#dab484" })
hi(0, "ALEErrorSign", { fg = "#db4b4b" })
hi(0, "ALEWarningSign", { fg = "#e0af68" })
hi(0, "AerialArrayIcon", { link = "LspKindArray" })
hi(0, "AerialBooleanIcon", { link = "LspKindBoolean" })
hi(0, "AerialClassIcon", { link = "LspKindClass" })
hi(0, "AerialColorIcon", { link = "LspKindColor" })
hi(0, "AerialConstantIcon", { link = "LspKindConstant" })
hi(0, "AerialConstructorIcon", { link = "LspKindConstructor" })
hi(0, "AerialEnumIcon", { link = "LspKindEnum" })
hi(0, "AerialEnumMemberIcon", { link = "LspKindEnumMember" })
hi(0, "AerialEventIcon", { link = "LspKindEvent" })
hi(0, "AerialFieldIcon", { link = "LspKindField" })
hi(0, "AerialFileIcon", { link = "LspKindFile" })
hi(0, "AerialFolderIcon", { link = "LspKindFolder" })
hi(0, "AerialFunctionIcon", { link = "LspKindFunction" })
hi(0, "AerialGuide", { fg = "#3b4261" })
hi(0, "AerialInterfaceIcon", { link = "LspKindInterface" })
hi(0, "AerialKeyIcon", { link = "LspKindKey" })
hi(0, "AerialKeywordIcon", { link = "LspKindKeyword" })
hi(0, "AerialLine", { link = "LspInlayHint" })
hi(0, "AerialMethodIcon", { link = "LspKindMethod" })
hi(0, "AerialModuleIcon", { link = "LspKindModule" })
hi(0, "AerialNamespaceIcon", { link = "LspKindNamespace" })
hi(0, "AerialNormal", { fg = "#c0caf5" })
hi(0, "AerialNullIcon", { link = "LspKindNull" })
hi(0, "AerialNumberIcon", { link = "LspKindNumber" })
hi(0, "AerialObjectIcon", { link = "LspKindObject" })
hi(0, "AerialOperatorIcon", { link = "LspKindOperator" })
hi(0, "AerialPackageIcon", { link = "LspKindPackage" })
hi(0, "AerialPropertyIcon", { link = "LspKindProperty" })
hi(0, "AerialReferenceIcon", { link = "LspKindReference" })
hi(0, "AerialSnippetIcon", { link = "LspKindSnippet" })
hi(0, "AerialStringIcon", { link = "LspKindString" })
hi(0, "AerialStructIcon", { link = "LspKindStruct" })
hi(0, "AerialTextIcon", { link = "LspKindText" })
hi(0, "AerialTypeParameterIcon", { link = "LspKindTypeParameter" })
hi(0, "AerialUnitIcon", { link = "LspKindUnit" })
hi(0, "AerialValueIcon", { link = "LspKindValue" })
hi(0, "AerialVariableIcon", { link = "LspKindVariable" })
hi(0, "AlphaButtons", { fg = "#7dcfff" })
hi(0, "AlphaFooter", { fg = "#2ac3de" })
hi(0, "AlphaHeader", { fg = "#7aa2f7" })
hi(0, "AlphaHeaderLabel", { fg = "#ff9e64" })
hi(0, "AlphaShortcut", { fg = "#ff9e64" })
hi(0, "BlinkCmpDoc", { bg = "#1f2335", fg = "#c0caf5" })
hi(0, "BlinkCmpDocBorder", { bg = "#1f2335", fg = "#29a4bd" })
hi(0, "BlinkCmpGhostText", { fg = "#414868" })
hi(0, "BlinkCmpKindArray", { link = "LspKindArray" })
hi(0, "BlinkCmpKindBoolean", { link = "LspKindBoolean" })
hi(0, "BlinkCmpKindClass", { link = "LspKindClass" })
hi(0, "BlinkCmpKindCodeium", { fg = "#1abc9c" })
hi(0, "BlinkCmpKindColor", { link = "LspKindColor" })
hi(0, "BlinkCmpKindConstant", { link = "LspKindConstant" })
hi(0, "BlinkCmpKindConstructor", { link = "LspKindConstructor" })
hi(0, "BlinkCmpKindCopilot", { fg = "#1abc9c" })
hi(0, "BlinkCmpKindDefault", { fg = "#a9b1d6" })
hi(0, "BlinkCmpKindEnum", { link = "LspKindEnum" })
hi(0, "BlinkCmpKindEnumMember", { link = "LspKindEnumMember" })
hi(0, "BlinkCmpKindEvent", { link = "LspKindEvent" })
hi(0, "BlinkCmpKindField", { link = "LspKindField" })
hi(0, "BlinkCmpKindFile", { link = "LspKindFile" })
hi(0, "BlinkCmpKindFolder", { link = "LspKindFolder" })
hi(0, "BlinkCmpKindFunction", { link = "LspKindFunction" })
hi(0, "BlinkCmpKindInterface", { link = "LspKindInterface" })
hi(0, "BlinkCmpKindKey", { link = "LspKindKey" })
hi(0, "BlinkCmpKindKeyword", { link = "LspKindKeyword" })
hi(0, "BlinkCmpKindMethod", { link = "LspKindMethod" })
hi(0, "BlinkCmpKindModule", { link = "LspKindModule" })
hi(0, "BlinkCmpKindNamespace", { link = "LspKindNamespace" })
hi(0, "BlinkCmpKindNull", { link = "LspKindNull" })
hi(0, "BlinkCmpKindNumber", { link = "LspKindNumber" })
hi(0, "BlinkCmpKindObject", { link = "LspKindObject" })
hi(0, "BlinkCmpKindOperator", { link = "LspKindOperator" })
hi(0, "BlinkCmpKindPackage", { link = "LspKindPackage" })
hi(0, "BlinkCmpKindProperty", { link = "LspKindProperty" })
hi(0, "BlinkCmpKindReference", { link = "LspKindReference" })
hi(0, "BlinkCmpKindSnippet", { link = "LspKindSnippet" })
hi(0, "BlinkCmpKindString", { link = "LspKindString" })
hi(0, "BlinkCmpKindStruct", { link = "LspKindStruct" })
hi(0, "BlinkCmpKindSupermaven", { fg = "#1abc9c" })
hi(0, "BlinkCmpKindTabNine", { fg = "#1abc9c" })
hi(0, "BlinkCmpKindText", { link = "LspKindText" })
hi(0, "BlinkCmpKindTypeParameter", { link = "LspKindTypeParameter" })
hi(0, "BlinkCmpKindUnit", { link = "LspKindUnit" })
hi(0, "BlinkCmpKindValue", { link = "LspKindValue" })
hi(0, "BlinkCmpKindVariable", { link = "LspKindVariable" })
hi(0, "BlinkCmpLabel", { fg = "#c0caf5" })
hi(0, "BlinkCmpLabelDeprecated", { fg = "#3b4261", strikethrough = true })
hi(0, "BlinkCmpLabelMatch", { fg = "#2ac3de" })
hi(0, "BlinkCmpMenu", { bg = "#1f2335", fg = "#c0caf5" })
hi(0, "BlinkCmpMenuBorder", { bg = "#1f2335", fg = "#29a4bd" })
hi(0, "BlinkCmpSignatureHelp", { bg = "#1f2335", fg = "#c0caf5" })
hi(0, "BlinkCmpSignatureHelpBorder", { bg = "#1f2335", fg = "#29a4bd" })
hi(0, "Bold", { bold = true, fg = "#c0caf5" })
hi(0, "BufferAlternate", { bg = "#3b4261", fg = "#c0caf5" })
hi(0, "BufferAlternateERROR", { bg = "#3b4261", fg = "#db4b4b" })
hi(0, "BufferAlternateHINT", { bg = "#3b4261", fg = "#1abc9c" })
hi(0, "BufferAlternateINFO", { bg = "#3b4261", fg = "#0db9d7" })
hi(0, "BufferAlternateIndex", { bg = "#3b4261", fg = "#0db9d7" })
hi(0, "BufferAlternateMod", { bg = "#3b4261", fg = "#e0af68" })
hi(0, "BufferAlternateSign", { bg = "#3b4261", fg = "#0db9d7" })
hi(0, "BufferAlternateTarget", { bg = "#3b4261", fg = "#f7768e" })
hi(0, "BufferAlternateWARN", { bg = "#3b4261", fg = "#e0af68" })
hi(0, "BufferCurrent", { bg = "#24283b", fg = "#c0caf5" })
hi(0, "BufferCurrentERROR", { bg = "#24283b", fg = "#db4b4b" })
hi(0, "BufferCurrentHINT", { bg = "#24283b", fg = "#1abc9c" })
hi(0, "BufferCurrentINFO", { bg = "#24283b", fg = "#0db9d7" })
hi(0, "BufferCurrentIndex", { bg = "#24283b", fg = "#0db9d7" })
hi(0, "BufferCurrentMod", { bg = "#24283b", fg = "#e0af68" })
hi(0, "BufferCurrentSign", { bg = "#24283b", fg = "#24283b" })
hi(0, "BufferCurrentTarget", { bg = "#24283b", fg = "#f7768e" })
hi(0, "BufferCurrentWARN", { bg = "#24283b", fg = "#e0af68" })
hi(0, "BufferInactive", { bg = "#262a3e", fg = "#636a8d" })
hi(0, "BufferInactiveERROR", { bg = "#262a3e", fg = "#b64448" })
hi(0, "BufferInactiveHINT", { bg = "#262a3e", fg = "#1c9e89" })
hi(0, "BufferInactiveINFO", { bg = "#262a3e", fg = "#129cb8" })
hi(0, "BufferInactiveIndex", { bg = "#262a3e", fg = "#737aa2" })
hi(0, "BufferInactiveMod", { bg = "#262a3e", fg = "#ba945f" })
hi(0, "BufferInactiveSign", { bg = "#262a3e", fg = "#24283b" })
hi(0, "BufferInactiveTarget", { bg = "#262a3e", fg = "#f7768e" })
hi(0, "BufferInactiveWARN", { bg = "#262a3e", fg = "#ba945f" })
hi(0, "BufferLineIndicatorSelected", { fg = "#6183bb" })
hi(0, "BufferOffset", { bg = "#1f2335", fg = "#737aa2" })
hi(0, "BufferTabpageFill", { bg = "#282d41", fg = "#737aa2" })
hi(0, "BufferTabpages", { bg = "#1f2335" })
hi(0, "BufferVisible", { bg = "#1f2335", fg = "#c0caf5" })
hi(0, "BufferVisibleERROR", { bg = "#1f2335", fg = "#db4b4b" })
hi(0, "BufferVisibleHINT", { bg = "#1f2335", fg = "#1abc9c" })
hi(0, "BufferVisibleINFO", { bg = "#1f2335", fg = "#0db9d7" })
hi(0, "BufferVisibleIndex", { bg = "#1f2335", fg = "#0db9d7" })
hi(0, "BufferVisibleMod", { bg = "#1f2335", fg = "#e0af68" })
hi(0, "BufferVisibleSign", { bg = "#1f2335", fg = "#0db9d7" })
hi(0, "BufferVisibleTarget", { bg = "#1f2335", fg = "#f7768e" })
hi(0, "BufferVisibleWARN", { bg = "#1f2335", fg = "#e0af68" })
hi(0, "Character", { fg = "#9ece6a" })
hi(0, "CmpDocumentation", { bg = "#1f2335", fg = "#c0caf5" })
hi(0, "CmpDocumentationBorder", { bg = "#1f2335", fg = "#29a4bd" })
hi(0, "CmpGhostText", { fg = "#414868" })
hi(0, "CmpItemAbbr", { fg = "#c0caf5" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#3b4261", strikethrough = true })
hi(0, "CmpItemAbbrMatch", { fg = "#2ac3de" })
hi(0, "CmpItemAbbrMatchFuzzy", { fg = "#2ac3de" })
hi(0, "CmpItemKindArray", { link = "LspKindArray" })
hi(0, "CmpItemKindBoolean", { link = "LspKindBoolean" })
hi(0, "CmpItemKindClass", { link = "LspKindClass" })
hi(0, "CmpItemKindCodeium", { fg = "#1abc9c" })
hi(0, "CmpItemKindColor", { link = "LspKindColor" })
hi(0, "CmpItemKindConstant", { link = "LspKindConstant" })
hi(0, "CmpItemKindConstructor", { link = "LspKindConstructor" })
hi(0, "CmpItemKindCopilot", { fg = "#1abc9c" })
hi(0, "CmpItemKindDefault", { fg = "#a9b1d6" })
hi(0, "CmpItemKindEnum", { link = "LspKindEnum" })
hi(0, "CmpItemKindEnumMember", { link = "LspKindEnumMember" })
hi(0, "CmpItemKindEvent", { link = "LspKindEvent" })
hi(0, "CmpItemKindField", { link = "LspKindField" })
hi(0, "CmpItemKindFile", { link = "LspKindFile" })
hi(0, "CmpItemKindFolder", { link = "LspKindFolder" })
hi(0, "CmpItemKindFunction", { link = "LspKindFunction" })
hi(0, "CmpItemKindInterface", { link = "LspKindInterface" })
hi(0, "CmpItemKindKey", { link = "LspKindKey" })
hi(0, "CmpItemKindKeyword", { link = "LspKindKeyword" })
hi(0, "CmpItemKindMethod", { link = "LspKindMethod" })
hi(0, "CmpItemKindModule", { link = "LspKindModule" })
hi(0, "CmpItemKindNamespace", { link = "LspKindNamespace" })
hi(0, "CmpItemKindNull", { link = "LspKindNull" })
hi(0, "CmpItemKindNumber", { link = "LspKindNumber" })
hi(0, "CmpItemKindObject", { link = "LspKindObject" })
hi(0, "CmpItemKindOperator", { link = "LspKindOperator" })
hi(0, "CmpItemKindPackage", { link = "LspKindPackage" })
hi(0, "CmpItemKindProperty", { link = "LspKindProperty" })
hi(0, "CmpItemKindReference", { link = "LspKindReference" })
hi(0, "CmpItemKindSnippet", { link = "LspKindSnippet" })
hi(0, "CmpItemKindString", { link = "LspKindString" })
hi(0, "CmpItemKindStruct", { link = "LspKindStruct" })
hi(0, "CmpItemKindSupermaven", { fg = "#1abc9c" })
hi(0, "CmpItemKindTabNine", { fg = "#1abc9c" })
hi(0, "CmpItemKindText", { link = "LspKindText" })
hi(0, "CmpItemKindTypeParameter", { link = "LspKindTypeParameter" })
hi(0, "CmpItemKindUnit", { link = "LspKindUnit" })
hi(0, "CmpItemKindValue", { link = "LspKindValue" })
hi(0, "CmpItemKindVariable", { link = "LspKindVariable" })
hi(0, "CmpItemMenu", { fg = "#565f89" })
hi(0, "CodeBlock", { bg = "#1f2335" })
hi(0, "CodeiumSuggestion", { fg = "#414868" })
hi(0, "ColorColumn", { bg = "#1d202f" })
hi(0, "Comment", { fg = "#565f89", italic = true })
hi(0, "Conceal", { fg = "#737aa2" })
hi(0, "Constant", { fg = "#ff9e64" })
hi(0, "CopilotAnnotation", { fg = "#414868" })
hi(0, "CopilotSuggestion", { fg = "#414868" })
hi(0, "CurSearch", { link = "IncSearch" })
hi(0, "Cursor", { bg = "#c0caf5", fg = "#24283b" })
hi(0, "CursorColumn", { bg = "#292e42" })
hi(0, "CursorIM", { bg = "#c0caf5", fg = "#24283b" })
hi(0, "CursorLine", { bg = "#292e42" })
hi(0, "CursorLineNr", { bold = true, fg = "#ff9e64" })
hi(0, "DapStoppedLine", { bg = "#373640" })
hi(0, "DashboardDesc", { fg = "#7dcfff" })
hi(0, "DashboardFiles", { fg = "#7aa2f7" })
hi(0, "DashboardFooter", { fg = "#2ac3de" })
hi(0, "DashboardHeader", { fg = "#7aa2f7" })
hi(0, "DashboardIcon", { fg = "#7dcfff" })
hi(0, "DashboardKey", { fg = "#ff9e64" })
hi(0, "DashboardMruIcon", { fg = "#9d7cd8" })
hi(0, "DashboardMruTitle", { fg = "#7dcfff" })
hi(0, "DashboardProjectIcon", { fg = "#e0af68" })
hi(0, "DashboardProjectTitle", { fg = "#7dcfff" })
hi(0, "DashboardProjectTitleIcon", { fg = "#ff9e64" })
hi(0, "DashboardShortCut", { fg = "#7dcfff" })
hi(0, "DashboardShortCutIcon", { fg = "#bb9af7" })
hi(0, "Debug", { fg = "#ff9e64" })
hi(0, "DefinitionCount", { fg = "#9d7cd8" })
hi(0, "DefinitionIcon", { fg = "#7aa2f7" })
hi(0, "Delimiter", { link = "Special" })
hi(0, "DiagnosticError", { fg = "#db4b4b" })
hi(0, "DiagnosticHint", { fg = "#1abc9c" })
hi(0, "DiagnosticInfo", { fg = "#0db9d7" })
hi(0, "DiagnosticInformation", { link = "DiagnosticInfo" })
hi(0, "DiagnosticUnderlineError", { sp = "#db4b4b", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#1abc9c", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#0db9d7", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#e0af68", undercurl = true })
hi(0, "DiagnosticUnnecessary", { fg = "#414868" })
hi(0, "DiagnosticVirtualTextError", { bg = "#362c3d", fg = "#db4b4b" })
hi(0, "DiagnosticVirtualTextHint", { bg = "#233745", fg = "#1abc9c" })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#22374b", fg = "#0db9d7" })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#373640", fg = "#e0af68" })
hi(0, "DiagnosticWarn", { fg = "#e0af68" })
hi(0, "DiagnosticWarning", { link = "DiagnosticWarn" })
hi(0, "DiffAdd", { bg = "#283b4d" })
hi(0, "DiffChange", { bg = "#272d43" })
hi(0, "DiffDelete", { bg = "#3f2d3d" })
hi(0, "DiffText", { bg = "#394b70" })
hi(0, "Directory", { fg = "#7aa2f7" })
hi(0, "EndOfBuffer", { fg = "#24283b" })
hi(0, "Error", { fg = "#db4b4b" })
hi(0, "ErrorMsg", { fg = "#db4b4b" })
hi(0, "FlashBackdrop", { fg = "#545c7e" })
hi(0, "FlashLabel", { bg = "#ff007c", bold = true, fg = "#c0caf5" })
hi(0, "FloatBorder", { bg = "#1f2335", fg = "#29a4bd" })
hi(0, "FloatTitle", { bg = "#1f2335", fg = "#29a4bd" })
hi(0, "FoldColumn", { bg = "#24283b", fg = "#565f89" })
hi(0, "Folded", { bg = "#3b4261", fg = "#7aa2f7" })
hi(0, "Foo", { bg = "#ff007c", fg = "#c0caf5" })
hi(0, "Function", { fg = "#7aa2f7" })
hi(0, "FzfLuaBorder", { bg = "#1f2335", fg = "#29a4bd" })
hi(0, "FzfLuaCursor", { link = "IncSearch" })
hi(0, "FzfLuaDirPart", { fg = "#a9b1d6" })
hi(0, "FzfLuaFilePart", { link = "FzfLuaFzfNormal" })
hi(0, "FzfLuaFzfCursorLine", { link = "Visual" })
hi(0, "FzfLuaFzfNormal", { fg = "#c0caf5" })
hi(0, "FzfLuaFzfPointer", { fg = "#ff007c" })
hi(0, "FzfLuaFzfSeparator", { bg = "#1f2335", fg = "#ff9e64" })
hi(0, "FzfLuaHeaderBind", { link = "@punctuation.special" })
hi(0, "FzfLuaHeaderText", { link = "Title" })
hi(0, "FzfLuaNormal", { bg = "#1f2335", fg = "#c0caf5" })
hi(0, "FzfLuaPath", { link = "Directory" })
hi(0, "FzfLuaPreviewTitle", { bg = "#1f2335", fg = "#29a4bd" })
hi(0, "FzfLuaTitle", { bg = "#1f2335", fg = "#ff9e64" })
hi(0, "GitGutterAdd", { fg = "#449dab" })
hi(0, "GitGutterAddLineNr", { fg = "#449dab" })
hi(0, "GitGutterChange", { fg = "#6183bb" })
hi(0, "GitGutterChangeLineNr", { fg = "#6183bb" })
hi(0, "GitGutterDelete", { fg = "#914c54" })
hi(0, "GitGutterDeleteLineNr", { fg = "#914c54" })
hi(0, "GitSignsAdd", { fg = "#449dab" })
hi(0, "GitSignsChange", { fg = "#6183bb" })
hi(0, "GitSignsDelete", { fg = "#914c54" })
hi(0, "GlyphPalette1", { fg = "#db4b4b" })
hi(0, "GlyphPalette2", { fg = "#9ece6a" })
hi(0, "GlyphPalette3", { fg = "#e0af68" })
hi(0, "GlyphPalette4", { fg = "#7aa2f7" })
hi(0, "GlyphPalette6", { fg = "#73daca" })
hi(0, "GlyphPalette7", { fg = "#c0caf5" })
hi(0, "GlyphPalette9", { fg = "#f7768e" })
hi(0, "GrugFarHelpHeader", { fg = "#565f89" })
hi(0, "GrugFarHelpHeaderKey", { fg = "#7dcfff" })
hi(0, "GrugFarInputLabel", { fg = "#2ac3de" })
hi(0, "GrugFarInputPlaceholder", { fg = "#545c7e" })
hi(0, "GrugFarResultsChangeIndicator", { fg = "#6183bb" })
hi(0, "GrugFarResultsHeader", { fg = "#ff9e64" })
hi(0, "GrugFarResultsLineColumn", { fg = "#545c7e" })
hi(0, "GrugFarResultsLineNo", { fg = "#545c7e" })
hi(0, "GrugFarResultsMatch", { bg = "#f7768e", fg = "#1d202f" })
hi(0, "GrugFarResultsStats", { fg = "#7aa2f7" })
hi(0, "Headline", { link = "Headline1" })
hi(0, "Headline1", { bg = "#282e44" })
hi(0, "Headline2", { bg = "#2d2f3d" })
hi(0, "Headline3", { bg = "#2a303d" })
hi(0, "Headline4", { bg = "#232f40" })
hi(0, "Headline5", { bg = "#2c2e44" })
hi(0, "Headline6", { bg = "#2a2c43" })
hi(0, "Headline7", { bg = "#2f2e3d" })
hi(0, "Headline8", { bg = "#2f2c3f" })
hi(0, "HopNextKey", { bold = true, fg = "#ff007c" })
hi(0, "HopNextKey1", { bold = true, fg = "#0db9d7" })
hi(0, "HopNextKey2", { fg = "#167f99" })
hi(0, "HopUnmatched", { fg = "#545c7e" })
hi(0, "IblIndent", { fg = "#3b4261", nocombine = true })
hi(0, "IblScope", { fg = "#2ac3de", nocombine = true })
hi(0, "Identifier", { fg = "#bb9af7" })
hi(0, "IlluminatedWordRead", { bg = "#3b4261" })
hi(0, "IlluminatedWordText", { bg = "#3b4261" })
hi(0, "IlluminatedWordWrite", { bg = "#3b4261" })
hi(0, "IncSearch", { bg = "#ff9e64", fg = "#1d202f" })
hi(0, "IndentBlanklineChar", { fg = "#3b4261", nocombine = true })
hi(0, "IndentBlanklineContextChar", { fg = "#2ac3de", nocombine = true })
hi(0, "IndentLine", { fg = "#3b4261", nocombine = true })
hi(0, "IndentLineCurrent", { fg = "#2ac3de", nocombine = true })
hi(0, "Italic", { fg = "#c0caf5", italic = true })
hi(0, "Keyword", { fg = "#7dcfff", italic = true })
hi(0, "LazyProgressDone", { bold = true, fg = "#ff007c" })
hi(0, "LazyProgressTodo", { bold = true, fg = "#3b4261" })
hi(0, "LeapBackdrop", { fg = "#545c7e" })
hi(0, "LeapLabel", { bold = true, fg = "#ff007c" })
hi(0, "LeapMatch", { bg = "#ff007c", bold = true, fg = "#c0caf5" })
hi(0, "LineNr", { fg = "#3b4261" })
hi(0, "LineNrAbove", { fg = "#3b4261" })
hi(0, "LineNrBelow", { fg = "#3b4261" })
hi(0, "LspCodeLens", { fg = "#565f89" })
hi(0, "LspFloatWinBorder", { fg = "#29a4bd" })
hi(0, "LspFloatWinNormal", { bg = "#1f2335" })
hi(0, "LspInfoBorder", { bg = "#1f2335", fg = "#29a4bd" })
hi(0, "LspInlayHint", { bg = "#262c40", fg = "#545c7e" })
hi(0, "LspKindArray", { link = "@punctuation.bracket" })
hi(0, "LspKindBoolean", { link = "@boolean" })
hi(0, "LspKindClass", { link = "@type" })
hi(0, "LspKindColor", { link = "Special" })
hi(0, "LspKindConstant", { link = "@constant" })
hi(0, "LspKindConstructor", { link = "@constructor" })
hi(0, "LspKindEnum", { link = "@lsp.type.enum" })
hi(0, "LspKindEnumMember", { link = "@lsp.type.enumMember" })
hi(0, "LspKindEvent", { link = "Special" })
hi(0, "LspKindField", { link = "@variable.member" })
hi(0, "LspKindFile", { link = "Normal" })
hi(0, "LspKindFolder", { link = "Directory" })
hi(0, "LspKindFunction", { link = "@function" })
hi(0, "LspKindInterface", { link = "@lsp.type.interface" })
hi(0, "LspKindKey", { link = "@variable.member" })
hi(0, "LspKindKeyword", { link = "@lsp.type.keyword" })
hi(0, "LspKindMethod", { link = "@function.method" })
hi(0, "LspKindModule", { link = "@module" })
hi(0, "LspKindNamespace", { link = "@module" })
hi(0, "LspKindNull", { link = "@constant.builtin" })
hi(0, "LspKindNumber", { link = "@number" })
hi(0, "LspKindObject", { link = "@constant" })
hi(0, "LspKindOperator", { link = "@operator" })
hi(0, "LspKindPackage", { link = "@module" })
hi(0, "LspKindProperty", { link = "@property" })
hi(0, "LspKindReference", { link = "@markup.link" })
hi(0, "LspKindSnippet", { link = "Conceal" })
hi(0, "LspKindString", { link = "@string" })
hi(0, "LspKindStruct", { link = "@lsp.type.struct" })
hi(0, "LspKindText", { link = "@markup" })
hi(0, "LspKindTypeParameter", { link = "@lsp.type.typeParameter" })
hi(0, "LspKindUnit", { link = "@lsp.type.struct" })
hi(0, "LspKindValue", { link = "@string" })
hi(0, "LspKindVariable", { link = "@variable" })
hi(0, "LspReferenceRead", { bg = "#3b4261" })
hi(0, "LspReferenceText", { bg = "#3b4261" })
hi(0, "LspReferenceWrite", { bg = "#3b4261" })
hi(0, "LspSagaBorderTitle", { fg = "#7dcfff" })
hi(0, "LspSagaCodeActionBorder", { fg = "#7aa2f7" })
hi(0, "LspSagaCodeActionContent", { fg = "#9d7cd8" })
hi(0, "LspSagaCodeActionTitle", { fg = "#2ac3de" })
hi(0, "LspSagaDefPreviewBorder", { fg = "#9ece6a" })
hi(0, "LspSagaFinderSelection", { fg = "#2e3c64" })
hi(0, "LspSagaHoverBorder", { fg = "#7aa2f7" })
hi(0, "LspSagaRenameBorder", { fg = "#9ece6a" })
hi(0, "LspSagaSignatureHelpBorder", { fg = "#f7768e" })
hi(0, "LspSignatureActiveParameter", { bg = "#28304b", bold = true })
hi(0, "MatchParen", { bold = true, fg = "#ff9e64" })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hi(0, "MiniClueBorder", { link = "FloatBorder" })
hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniClueTitle", { link = "FloatTitle" })
hi(0, "MiniCompletionActiveParameter", { underline = true })
hi(0, "MiniCursorword", { bg = "#3b4261" })
hi(0, "MiniCursorwordCurrent", { bg = "#3b4261" })
hi(0, "MiniDepsChangeAdded", { link = "diffAdded" })
hi(0, "MiniDepsChangeRemoved", { link = "diffRemoved" })
hi(0, "MiniDepsTitleError", { bg = "#914c54", fg = "#1d202f" })
hi(0, "MiniDepsTitleSame", { link = "Comment" })
hi(0, "MiniDepsTitleUpdate", { bg = "#449dab", fg = "#1d202f" })
hi(0, "MiniDiffSignAdd", { fg = "#449dab" })
hi(0, "MiniDiffSignChange", { fg = "#6183bb" })
hi(0, "MiniDiffSignDelete", { fg = "#914c54" })
hi(0, "MiniFilesFile", { fg = "#c0caf5" })
hi(0, "MiniFilesTitleFocused", { bg = "#1f2335", bold = true, fg = "#29a4bd" })
hi(0, "MiniHipatternsFixme", { bg = "#db4b4b", bold = true, fg = "#1d202f" })
hi(0, "MiniHipatternsHack", { bg = "#e0af68", bold = true, fg = "#1d202f" })
hi(0, "MiniHipatternsNote", { bg = "#1abc9c", bold = true, fg = "#1d202f" })
hi(0, "MiniHipatternsTodo", { bg = "#0db9d7", bold = true, fg = "#1d202f" })
hi(0, "MiniHipatterns_000000_bg", { bg = "#000000", fg = "#ffffff" })
hi(0, "MiniHipatterns_0e1420_bg", { bg = "#0e1420", fg = "#ffffff" })
hi(0, "MiniHipatterns_0f3856_bg", { bg = "#0f3856", fg = "#ffffff" })
hi(0, "MiniHipatterns_103a3c_bg", { bg = "#103a3c", fg = "#ffffff" })
hi(0, "MiniHipatterns_111726_bg", { bg = "#111726", fg = "#ffffff" })
hi(0, "MiniHipatterns_111827_bg", { bg = "#111827", fg = "#ffffff" })
hi(0, "MiniHipatterns_1b1b1b_bg", { bg = "#1b1b1b", fg = "#ffffff" })
hi(0, "MiniHipatterns_1e1d2d_bg", { bg = "#1e1d2d", fg = "#ffffff" })
hi(0, "MiniHipatterns_1f2937_bg", { bg = "#1f2937", fg = "#ffffff" })
hi(0, "MiniHipatterns_1f343d_bg", { bg = "#1f343d", fg = "#ffffff" })
hi(0, "MiniHipatterns_223249_bg", { bg = "#223249", fg = "#ffffff" })
hi(0, "MiniHipatterns_268bd3_bg", { bg = "#268bd3", fg = "#000000" })
hi(0, "MiniHipatterns_28304d_bg", { bg = "#28304d", fg = "#ffffff" })
hi(0, "MiniHipatterns_29a298_bg", { bg = "#29a298", fg = "#000000" })
hi(0, "MiniHipatterns_2d4f67_bg", { bg = "#2d4f67", fg = "#ffffff" })
hi(0, "MiniHipatterns_303030_bg", { bg = "#303030", fg = "#ffffff" })
hi(0, "MiniHipatterns_305777_bg", { bg = "#305777", fg = "#ffffff" })
hi(0, "MiniHipatterns_332700_bg", { bg = "#332700", fg = "#ffffff" })
hi(0, "MiniHipatterns_334155_bg", { bg = "#334155", fg = "#ffffff" })
hi(0, "MiniHipatterns_37393d_bg", { bg = "#37393d", fg = "#ffffff" })
hi(0, "MiniHipatterns_373e50_bg", { bg = "#373e50", fg = "#ffffff" })
hi(0, "MiniHipatterns_374151_bg", { bg = "#374151", fg = "#ffffff" })
hi(0, "MiniHipatterns_39adb5_bg", { bg = "#39adb5", fg = "#000000" })
hi(0, "MiniHipatterns_3b2c3c_bg", { bg = "#3b2c3c", fg = "#ffffff" })
hi(0, "MiniHipatterns_42464e_bg", { bg = "#42464e", fg = "#ffffff" })
hi(0, "MiniHipatterns_424674_bg", { bg = "#424674", fg = "#ffffff" })
hi(0, "MiniHipatterns_445f96_bg", { bg = "#445f96", fg = "#ffffff" })
hi(0, "MiniHipatterns_467c7b_bg", { bg = "#467c7b", fg = "#ffffff" })
hi(0, "MiniHipatterns_4b4a1c_bg", { bg = "#4b4a1c", fg = "#ffffff" })
hi(0, "MiniHipatterns_4b5563_bg", { bg = "#4b5563", fg = "#ffffff" })
hi(0, "MiniHipatterns_4b6987_bg", { bg = "#4b6987", fg = "#ffffff" })
hi(0, "MiniHipatterns_4c384c_bg", { bg = "#4c384c", fg = "#ffffff" })
hi(0, "MiniHipatterns_51afef_bg", { bg = "#51afef", fg = "#000000" })
hi(0, "MiniHipatterns_537788_bg", { bg = "#537788", fg = "#ffffff" })
hi(0, "MiniHipatterns_565c64_bg", { bg = "#565c64", fg = "#ffffff" })
hi(0, "MiniHipatterns_56b6c2_bg", { bg = "#56b6c2", fg = "#000000" })
hi(0, "MiniHipatterns_570f0e_bg", { bg = "#570f0e", fg = "#ffffff" })
hi(0, "MiniHipatterns_586e62_bg", { bg = "#586e62", fg = "#ffffff" })
hi(0, "MiniHipatterns_597b60_bg", { bg = "#597b60", fg = "#ffffff" })
hi(0, "MiniHipatterns_5e5f65_bg", { bg = "#5e5f65", fg = "#ffffff" })
hi(0, "MiniHipatterns_5e908e_bg", { bg = "#5e908e", fg = "#000000" })
hi(0, "MiniHipatterns_5f7d9b_bg", { bg = "#5f7d9b", fg = "#000000" })
hi(0, "MiniHipatterns_658594_bg", { bg = "#658594", fg = "#000000" })
hi(0, "MiniHipatterns_695d57_bg", { bg = "#695d57", fg = "#ffffff" })
hi(0, "MiniHipatterns_69827b_bg", { bg = "#69827b", fg = "#000000" })
hi(0, "MiniHipatterns_6a824f_bg", { bg = "#6a824f", fg = "#000000" })
hi(0, "MiniHipatterns_6b2325_bg", { bg = "#6b2325", fg = "#ffffff" })
hi(0, "MiniHipatterns_6b7280_bg", { bg = "#6b7280", fg = "#ffffff" })
hi(0, "MiniHipatterns_6c805c_bg", { bg = "#6c805c", fg = "#000000" })
hi(0, "MiniHipatterns_6e6b66_bg", { bg = "#6e6b66", fg = "#ffffff" })
hi(0, "MiniHipatterns_6f5f4b_bg", { bg = "#6f5f4b", fg = "#ffffff" })
hi(0, "MiniHipatterns_716e61_bg", { bg = "#716e61", fg = "#ffffff" })
hi(0, "MiniHipatterns_738199_bg", { bg = "#738199", fg = "#000000" })
hi(0, "MiniHipatterns_746862_bg", { bg = "#746862", fg = "#ffffff" })
hi(0, "MiniHipatterns_746d6a_bg", { bg = "#746d6a", fg = "#ffffff" })
hi(0, "MiniHipatterns_75998e_bg", { bg = "#75998e", fg = "#000000" })
hi(0, "MiniHipatterns_787878_bg", { bg = "#787878", fg = "#000000" })
hi(0, "MiniHipatterns_7a8382_bg", { bg = "#7a8382", fg = "#000000" })
hi(0, "MiniHipatterns_7aa89f_bg", { bg = "#7aa89f", fg = "#000000" })
hi(0, "MiniHipatterns_7e8e8e_bg", { bg = "#7e8e8e", fg = "#000000" })
hi(0, "MiniHipatterns_7f605c_bg", { bg = "#7f605c", fg = "#ffffff" })
hi(0, "MiniHipatterns_7fb4ca_bg", { bg = "#7fb4ca", fg = "#000000" })
hi(0, "MiniHipatterns_808080_bg", { bg = "#808080", fg = "#000000" })
hi(0, "MiniHipatterns_827f79_bg", { bg = "#827f79", fg = "#000000" })
hi(0, "MiniHipatterns_857e7b_bg", { bg = "#857e7b", fg = "#000000" })
hi(0, "MiniHipatterns_8779a8_bg", { bg = "#8779a8", fg = "#000000" })
hi(0, "MiniHipatterns_879a39_bg", { bg = "#879a39", fg = "#000000" })
hi(0, "MiniHipatterns_87a987_bg", { bg = "#87a987", fg = "#000000" })
hi(0, "MiniHipatterns_899d79_bg", { bg = "#899d79", fg = "#000000" })
hi(0, "MiniHipatterns_89ddff_bg", { bg = "#89ddff", fg = "#000000" })
hi(0, "MiniHipatterns_938aa9_bg", { bg = "#938aa9", fg = "#000000" })
hi(0, "MiniHipatterns_969438_bg", { bg = "#969438", fg = "#000000" })
hi(0, "MiniHipatterns_976153_bg", { bg = "#976153", fg = "#ffffff" })
hi(0, "MiniHipatterns_98bb6c_bg", { bg = "#98bb6c", fg = "#000000" })
hi(0, "MiniHipatterns_98bc99_bg", { bg = "#98bc99", fg = "#000000" })
hi(0, "MiniHipatterns_9c7b9c_bg", { bg = "#9c7b9c", fg = "#000000" })
hi(0, "MiniHipatterns_9ca3af_bg", { bg = "#9ca3af", fg = "#000000" })
hi(0, "MiniHipatterns_9fb5c9_bg", { bg = "#9fb5c9", fg = "#000000" })
hi(0, "MiniHipatterns_a06c4e_bg", { bg = "#a06c4e", fg = "#000000" })
hi(0, "MiniHipatterns_a0713c_bg", { bg = "#a0713c", fg = "#000000" })
hi(0, "MiniHipatterns_a09996_bg", { bg = "#a09996", fg = "#000000" })
hi(0, "MiniHipatterns_a0a0a0_bg", { bg = "#a0a0a0", fg = "#000000" })
hi(0, "MiniHipatterns_a292a3_bg", { bg = "#a292a3", fg = "#000000" })
hi(0, "MiniHipatterns_a5b4fc_bg", { bg = "#a5b4fc", fg = "#000000" })
hi(0, "MiniHipatterns_a685a6_bg", { bg = "#a685a6", fg = "#000000" })
hi(0, "MiniHipatterns_a87678_bg", { bg = "#a87678", fg = "#000000" })
hi(0, "MiniHipatterns_a9a29f_bg", { bg = "#a9a29f", fg = "#000000" })
hi(0, "MiniHipatterns_ae81ff_bg", { bg = "#ae81ff", fg = "#000000" })
hi(0, "MiniHipatterns_b1b1d2_bg", { bg = "#b1b1d2", fg = "#000000" })
hi(0, "MiniHipatterns_b23b34_bg", { bg = "#b23b34", fg = "#ffffff" })
hi(0, "MiniHipatterns_b28069_bg", { bg = "#b28069", fg = "#000000" })
hi(0, "MiniHipatterns_b28500_bg", { bg = "#b28500", fg = "#000000" })
hi(0, "MiniHipatterns_b2aba8_bg", { bg = "#b2aba8", fg = "#000000" })
hi(0, "MiniHipatterns_b3816a_bg", { bg = "#b3816a", fg = "#000000" })
hi(0, "MiniHipatterns_b3adab_bg", { bg = "#b3adab", fg = "#000000" })
hi(0, "MiniHipatterns_b5e8b0_bg", { bg = "#b5e8b0", fg = "#000000" })
hi(0, "MiniHipatterns_b73242_bg", { bg = "#b73242", fg = "#ffffff" })
hi(0, "MiniHipatterns_b7856e_bg", { bg = "#b7856e", fg = "#000000" })
hi(0, "MiniHipatterns_b8b3b0_bg", { bg = "#b8b3b0", fg = "#000000" })
hi(0, "MiniHipatterns_b9b2af_bg", { bg = "#b9b2af", fg = "#000000" })
hi(0, "MiniHipatterns_bae6fd_bg", { bg = "#bae6fd", fg = "#000000" })
hi(0, "MiniHipatterns_bfc6d4_bg", { bg = "#bfc6d4", fg = "#000000" })
hi(0, "MiniHipatterns_c0b9b6_bg", { bg = "#c0b9b6", fg = "#000000" })
hi(0, "MiniHipatterns_c18f78_bg", { bg = "#c18f78", fg = "#000000" })
hi(0, "MiniHipatterns_c7c0bd_bg", { bg = "#c7c0bd", fg = "#000000" })
hi(0, "MiniHipatterns_c87b2e_bg", { bg = "#c87b2e", fg = "#000000" })
hi(0, "MiniHipatterns_c8c8c8_bg", { bg = "#c8c8c8", fg = "#000000" })
hi(0, "MiniHipatterns_cac3c0_bg", { bg = "#cac3c0", fg = "#000000" })
hi(0, "MiniHipatterns_cc836c_bg", { bg = "#cc836c", fg = "#000000" })
hi(0, "MiniHipatterns_cdc6c3_bg", { bg = "#cdc6c3", fg = "#000000" })
hi(0, "MiniHipatterns_d0c9c6_bg", { bg = "#d0c9c6", fg = "#000000" })
hi(0, "MiniHipatterns_d1cac7_bg", { bg = "#d1cac7", fg = "#000000" })
hi(0, "MiniHipatterns_d38a73_bg", { bg = "#d38a73", fg = "#000000" })
hi(0, "MiniHipatterns_d3ccc9_bg", { bg = "#d3ccc9", fg = "#000000" })
hi(0, "MiniHipatterns_d4d4f0_bg", { bg = "#d4d4f0", fg = "#000000" })
hi(0, "MiniHipatterns_d5dcd2_bg", { bg = "#d5dcd2", fg = "#000000" })
hi(0, "MiniHipatterns_d7474b_bg", { bg = "#d7474b", fg = "#000000" })
hi(0, "MiniHipatterns_d7d0cd_bg", { bg = "#d7d0cd", fg = "#000000" })
hi(0, "MiniHipatterns_d8d8d8_bg", { bg = "#d8d8d8", fg = "#000000" })
hi(0, "MiniHipatterns_d9a594_bg", { bg = "#d9a594", fg = "#000000" })
hi(0, "MiniHipatterns_d9d1ce_bg", { bg = "#d9d1ce", fg = "#000000" })
hi(0, "MiniHipatterns_d9d2cf_bg", { bg = "#d9d2cf", fg = "#000000" })
hi(0, "MiniHipatterns_da70ca_bg", { bg = "#da70ca", fg = "#000000" })
hi(0, "MiniHipatterns_db302d_bg", { bg = "#db302d", fg = "#000000" })
hi(0, "MiniHipatterns_dcd5d2_bg", { bg = "#dcd5d2", fg = "#000000" })
hi(0, "MiniHipatterns_ddd6fe_bg", { bg = "#ddd6fe", fg = "#000000" })
hi(0, "MiniHipatterns_debe97_bg", { bg = "#debe97", fg = "#000000" })
hi(0, "MiniHipatterns_ded7d4_bg", { bg = "#ded7d4", fg = "#000000" })
hi(0, "MiniHipatterns_dfd8d5_bg", { bg = "#dfd8d5", fg = "#000000" })
hi(0, "MiniHipatterns_e2dcd4_bg", { bg = "#e2dcd4", fg = "#000000" })
hi(0, "MiniHipatterns_e46876_bg", { bg = "#e46876", fg = "#000000" })
hi(0, "MiniHipatterns_e5e7eb_bg", { bg = "#e5e7eb", fg = "#000000" })
hi(0, "MiniHipatterns_e6c2c7_bg", { bg = "#e6c2c7", fg = "#000000" })
hi(0, "MiniHipatterns_e6dfdc_bg", { bg = "#e6dfdc", fg = "#000000" })
hi(0, "MiniHipatterns_e7e7e7_bg", { bg = "#e7e7e7", fg = "#000000" })
hi(0, "MiniHipatterns_e84444_bg", { bg = "#e84444", fg = "#000000" })
hi(0, "MiniHipatterns_eeeeee_bg", { bg = "#eeeeee", fg = "#000000" })
hi(0, "MiniHipatterns_f6f6f6_bg", { bg = "#f6f6f6", fg = "#000000" })
hi(0, "MiniHipatterns_f9fafb_bg", { bg = "#f9fafb", fg = "#000000" })
hi(0, "MiniHipatterns_fa8d3e_bg", { bg = "#fa8d3e", fg = "#000000" })
hi(0, "MiniHipatterns_fbc19d_bg", { bg = "#fbc19d", fg = "#000000" })
hi(0, "MiniHipatterns_fca5a5_bg", { bg = "#fca5a5", fg = "#000000" })
hi(0, "MiniHipatterns_fecdd3_bg", { bg = "#fecdd3", fg = "#000000" })
hi(0, "MiniHipatterns_ffffff_bg", { bg = "#ffffff", fg = "#000000" })
hi(0, "MiniIconsAzure", { fg = "#0db9d7" })
hi(0, "MiniIconsBlue", { fg = "#7aa2f7" })
hi(0, "MiniIconsCyan", { fg = "#1abc9c" })
hi(0, "MiniIconsGreen", { fg = "#9ece6a" })
hi(0, "MiniIconsGrey", { fg = "#c0caf5" })
hi(0, "MiniIconsOrange", { fg = "#ff9e64" })
hi(0, "MiniIconsPurple", { fg = "#9d7cd8" })
hi(0, "MiniIconsRed", { fg = "#f7768e" })
hi(0, "MiniIconsYellow", { fg = "#e0af68" })
hi(0, "MiniIndentscopePrefix", { nocombine = true })
hi(0, "MiniIndentscopeSymbol", { fg = "#2ac3de", nocombine = true })
hi(0, "MiniJump", { bg = "#ff007c", fg = "#ffffff" })
hi(0, "MiniJump2dDim", { link = "Comment" })
hi(0, "MiniJump2dSpot", { bold = true, fg = "#ff007c", nocombine = true })
hi(0, "MiniJump2dSpotAhead", { bg = "#1f2335", fg = "#1abc9c", nocombine = true })
hi(0, "MiniJump2dSpotUnique", { bold = true, fg = "#ff9e64", nocombine = true })
hi(0, "MiniMapNormal", { link = "NormalFloat" })
hi(0, "MiniMapSymbolCount", { link = "Special" })
hi(0, "MiniMapSymbolLine", { link = "Title" })
hi(0, "MiniMapSymbolView", { link = "Delimiter" })
hi(0, "MiniPickBorderText", { bg = "#1f2335", fg = "#1abc9c" })
hi(0, "MiniPickCursor", { blend = 100, nocombine = true })
hi(0, "MiniPickPrompt", { bg = "#1f2335", fg = "#0db9d7" })
hi(0, "MiniSnippetsCurrent", { sp = "#e0af68", underdouble = true })
hi(0, "MiniSnippetsCurrentReplace", { sp = "#db4b4b", underdouble = true })
hi(0, "MiniSnippetsFinal", { sp = "#b3f6c0", underdouble = true })
hi(0, "MiniSnippetsUnvisited", { sp = "#1abc9c", underdouble = true })
hi(0, "MiniSnippetsVisited", { sp = "#0db9d7", underdouble = true })
hi(0, "MiniStarterCurrent", { nocombine = true })
hi(0, "MiniStarterFooter", { fg = "#e0af68", italic = true })
hi(0, "MiniStarterHeader", { fg = "#7aa2f7" })
hi(0, "MiniStarterInactive", { fg = "#565f89", italic = true })
hi(0, "MiniStarterItem", { bg = "#24283b", fg = "#c0caf5" })
hi(0, "MiniStarterItemBullet", { fg = "#29a4bd" })
hi(0, "MiniStarterItemPrefix", { fg = "#e0af68" })
hi(0, "MiniStarterQuery", { fg = "#0db9d7" })
hi(0, "MiniStarterSection", { fg = "#2ac3de" })
hi(0, "MiniStatuslineDevinfo", { bg = "#3b4261", fg = "#a9b1d6" })
hi(0, "MiniStatuslineFileinfo", { bg = "#3b4261", fg = "#a9b1d6" })
hi(0, "MiniStatuslineFilename", { bg = "#292e42", fg = "#a9b1d6" })
hi(0, "MiniStatuslineInactive", { bg = "#1f2335", fg = "#7aa2f7" })
hi(0, "MiniStatuslineModeCommand", { bg = "#e0af68", bold = true, fg = "#1d202f" })
hi(0, "MiniStatuslineModeInsert", { bg = "#9ece6a", bold = true, fg = "#1d202f" })
hi(0, "MiniStatuslineModeNormal", { bg = "#7aa2f7", bold = true, fg = "#1d202f" })
hi(0, "MiniStatuslineModeOther", { bg = "#1abc9c", bold = true, fg = "#1d202f" })
hi(0, "MiniStatuslineModeReplace", { bg = "#f7768e", bold = true, fg = "#1d202f" })
hi(0, "MiniStatuslineModeVisual", { bg = "#bb9af7", bold = true, fg = "#1d202f" })
hi(0, "MiniSurround", { bg = "#ff9e64", fg = "#1d202f" })
hi(0, "MiniTablineCurrent", { bg = "#3b4261", fg = "#c0caf5" })
hi(0, "MiniTablineFill", { bg = "#1d202f" })
hi(0, "MiniTablineHidden", { bg = "#1f2335", fg = "#737aa2" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#3b4261", fg = "#e0af68" })
hi(0, "MiniTablineModifiedHidden", { bg = "#1f2335", fg = "#a8875b" })
hi(0, "MiniTablineModifiedVisible", { bg = "#1f2335", fg = "#e0af68" })
hi(0, "MiniTablineTabpagesection", { bg = "#3b4261" })
hi(0, "MiniTablineVisible", { bg = "#1f2335", fg = "#c0caf5" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#f7768e" })
hi(0, "MiniTestPass", { bold = true, fg = "#9ece6a" })
hi(0, "MiniTrailspace", { bg = "#f7768e" })
hi(0, "ModeMsg", { bold = true, fg = "#a9b1d6" })
hi(0, "MoreMsg", { fg = "#7aa2f7" })
hi(0, "MsgArea", { fg = "#a9b1d6" })
hi(0, "NavicIconsArray", { link = "LspKindArray" })
hi(0, "NavicIconsBoolean", { link = "LspKindBoolean" })
hi(0, "NavicIconsClass", { link = "LspKindClass" })
hi(0, "NavicIconsColor", { link = "LspKindColor" })
hi(0, "NavicIconsConstant", { link = "LspKindConstant" })
hi(0, "NavicIconsConstructor", { link = "LspKindConstructor" })
hi(0, "NavicIconsEnum", { link = "LspKindEnum" })
hi(0, "NavicIconsEnumMember", { link = "LspKindEnumMember" })
hi(0, "NavicIconsEvent", { link = "LspKindEvent" })
hi(0, "NavicIconsField", { link = "LspKindField" })
hi(0, "NavicIconsFile", { link = "LspKindFile" })
hi(0, "NavicIconsFolder", { link = "LspKindFolder" })
hi(0, "NavicIconsFunction", { link = "LspKindFunction" })
hi(0, "NavicIconsInterface", { link = "LspKindInterface" })
hi(0, "NavicIconsKey", { link = "LspKindKey" })
hi(0, "NavicIconsKeyword", { link = "LspKindKeyword" })
hi(0, "NavicIconsMethod", { link = "LspKindMethod" })
hi(0, "NavicIconsModule", { link = "LspKindModule" })
hi(0, "NavicIconsNamespace", { link = "LspKindNamespace" })
hi(0, "NavicIconsNull", { link = "LspKindNull" })
hi(0, "NavicIconsNumber", { link = "LspKindNumber" })
hi(0, "NavicIconsObject", { link = "LspKindObject" })
hi(0, "NavicIconsOperator", { link = "LspKindOperator" })
hi(0, "NavicIconsPackage", { link = "LspKindPackage" })
hi(0, "NavicIconsProperty", { link = "LspKindProperty" })
hi(0, "NavicIconsReference", { link = "LspKindReference" })
hi(0, "NavicIconsSnippet", { link = "LspKindSnippet" })
hi(0, "NavicIconsString", { link = "LspKindString" })
hi(0, "NavicIconsStruct", { link = "LspKindStruct" })
hi(0, "NavicIconsText", { link = "LspKindText" })
hi(0, "NavicIconsTypeParameter", { link = "LspKindTypeParameter" })
hi(0, "NavicIconsUnit", { link = "LspKindUnit" })
hi(0, "NavicIconsValue", { link = "LspKindValue" })
hi(0, "NavicIconsVariable", { link = "LspKindVariable" })
hi(0, "NavicSeparator", { fg = "#c0caf5" })
hi(0, "NavicText", { fg = "#c0caf5" })
hi(0, "NeoTreeDimText", { fg = "#3b4261" })
hi(0, "NeoTreeFileName", { fg = "#a9b1d6" })
hi(0, "NeoTreeGitModified", { fg = "#ff9e64" })
hi(0, "NeoTreeGitStaged", { fg = "#73daca" })
hi(0, "NeoTreeGitUntracked", { fg = "#bb9af7" })
hi(0, "NeoTreeNormal", { bg = "#1f2335", fg = "#a9b1d6" })
hi(0, "NeoTreeNormalNC", { bg = "#1f2335", fg = "#a9b1d6" })
hi(0, "NeoTreeTabActive", { bg = "#1f2335", bold = true, fg = "#7aa2f7" })
hi(0, "NeoTreeTabInactive", { bg = "#191c2a", fg = "#545c7e" })
hi(0, "NeoTreeTabSeparatorActive", { bg = "#1f2335", fg = "#7aa2f7" })
hi(0, "NeoTreeTabSeparatorInactive", { bg = "#191c2a", fg = "#24283b" })
hi(0, "NeogitBranch", { fg = "#bb9af7" })
hi(0, "NeogitDiffAddHighlight", { bg = "#283b4d", fg = "#449dab" })
hi(0, "NeogitDiffContextHighlight", { bg = "#30354e", fg = "#a9b1d6" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#3f2d3d", fg = "#914c54" })
hi(0, "NeogitHunkHeader", { bg = "#292e42", fg = "#c0caf5" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#3b4261", fg = "#7aa2f7" })
hi(0, "NeogitRemote", { fg = "#9d7cd8" })
hi(0, "NeotestAdapterName", { bold = true, fg = "#9d7cd8" })
hi(0, "NeotestBorder", { fg = "#7aa2f7" })
hi(0, "NeotestDir", { fg = "#7aa2f7" })
hi(0, "NeotestExpandMarker", { fg = "#a9b1d6" })
hi(0, "NeotestFailed", { fg = "#f7768e" })
hi(0, "NeotestFile", { fg = "#1abc9c" })
hi(0, "NeotestFocused", { fg = "#e0af68" })
hi(0, "NeotestIndent", { fg = "#a9b1d6" })
hi(0, "NeotestMarked", { fg = "#7aa2f7" })
hi(0, "NeotestNamespace", { fg = "#41a6b5" })
hi(0, "NeotestPassed", { fg = "#9ece6a" })
hi(0, "NeotestRunning", { fg = "#e0af68" })
hi(0, "NeotestSkipped", { fg = "#7aa2f7" })
hi(0, "NeotestTarget", { fg = "#7aa2f7" })
hi(0, "NeotestTest", { fg = "#a9b1d6" })
hi(0, "NeotestWinSelect", { fg = "#7aa2f7" })
hi(0, "NoiceCmdlineIconInput", { fg = "#e0af68" })
hi(0, "NoiceCmdlineIconLua", { fg = "#2ac3de" })
hi(0, "NoiceCmdlinePopupBorderInput", { fg = "#e0af68" })
hi(0, "NoiceCmdlinePopupBorderLua", { fg = "#2ac3de" })
hi(0, "NoiceCmdlinePopupTitleInput", { fg = "#e0af68" })
hi(0, "NoiceCmdlinePopupTitleLua", { fg = "#2ac3de" })
hi(0, "NoiceCompletionItemKindArray", { link = "LspKindArray" })
hi(0, "NoiceCompletionItemKindBoolean", { link = "LspKindBoolean" })
hi(0, "NoiceCompletionItemKindClass", { link = "LspKindClass" })
hi(0, "NoiceCompletionItemKindColor", { link = "LspKindColor" })
hi(0, "NoiceCompletionItemKindConstant", { link = "LspKindConstant" })
hi(0, "NoiceCompletionItemKindConstructor", { link = "LspKindConstructor" })
hi(0, "NoiceCompletionItemKindDefault", { fg = "#a9b1d6" })
hi(0, "NoiceCompletionItemKindEnum", { link = "LspKindEnum" })
hi(0, "NoiceCompletionItemKindEnumMember", { link = "LspKindEnumMember" })
hi(0, "NoiceCompletionItemKindEvent", { link = "LspKindEvent" })
hi(0, "NoiceCompletionItemKindField", { link = "LspKindField" })
hi(0, "NoiceCompletionItemKindFile", { link = "LspKindFile" })
hi(0, "NoiceCompletionItemKindFolder", { link = "LspKindFolder" })
hi(0, "NoiceCompletionItemKindFunction", { link = "LspKindFunction" })
hi(0, "NoiceCompletionItemKindInterface", { link = "LspKindInterface" })
hi(0, "NoiceCompletionItemKindKey", { link = "LspKindKey" })
hi(0, "NoiceCompletionItemKindKeyword", { link = "LspKindKeyword" })
hi(0, "NoiceCompletionItemKindMethod", { link = "LspKindMethod" })
hi(0, "NoiceCompletionItemKindModule", { link = "LspKindModule" })
hi(0, "NoiceCompletionItemKindNamespace", { link = "LspKindNamespace" })
hi(0, "NoiceCompletionItemKindNull", { link = "LspKindNull" })
hi(0, "NoiceCompletionItemKindNumber", { link = "LspKindNumber" })
hi(0, "NoiceCompletionItemKindObject", { link = "LspKindObject" })
hi(0, "NoiceCompletionItemKindOperator", { link = "LspKindOperator" })
hi(0, "NoiceCompletionItemKindPackage", { link = "LspKindPackage" })
hi(0, "NoiceCompletionItemKindProperty", { link = "LspKindProperty" })
hi(0, "NoiceCompletionItemKindReference", { link = "LspKindReference" })
hi(0, "NoiceCompletionItemKindSnippet", { link = "LspKindSnippet" })
hi(0, "NoiceCompletionItemKindString", { link = "LspKindString" })
hi(0, "NoiceCompletionItemKindStruct", { link = "LspKindStruct" })
hi(0, "NoiceCompletionItemKindText", { link = "LspKindText" })
hi(0, "NoiceCompletionItemKindTypeParameter", { link = "LspKindTypeParameter" })
hi(0, "NoiceCompletionItemKindUnit", { link = "LspKindUnit" })
hi(0, "NoiceCompletionItemKindValue", { link = "LspKindValue" })
hi(0, "NoiceCompletionItemKindVariable", { link = "LspKindVariable" })
hi(0, "NonText", { fg = "#545c7e" })
hi(0, "Normal", { bg = "#24283b", fg = "#c0caf5" })
hi(0, "NormalFloat", { bg = "#1f2335", fg = "#c0caf5" })
hi(0, "NormalNC", { bg = "#24283b", fg = "#c0caf5" })
hi(0, "NormalSB", { bg = "#1f2335", fg = "#a9b1d6" })
hi(0, "NotifyBackground", { bg = "#24283b", fg = "#c0caf5" })
hi(0, "NotifyDEBUGBody", { bg = "#24283b", fg = "#c0caf5" })
hi(0, "NotifyDEBUGBorder", { bg = "#24283b", fg = "#333952" })
hi(0, "NotifyDEBUGIcon", { fg = "#565f89" })
hi(0, "NotifyDEBUGTitle", { fg = "#565f89" })
hi(0, "NotifyERRORBody", { bg = "#24283b", fg = "#c0caf5" })
hi(0, "NotifyERRORBorder", { bg = "#24283b", fg = "#5b3340" })
hi(0, "NotifyERRORIcon", { fg = "#db4b4b" })
hi(0, "NotifyERRORTitle", { fg = "#db4b4b" })
hi(0, "NotifyINFOBody", { bg = "#24283b", fg = "#c0caf5" })
hi(0, "NotifyINFOBorder", { bg = "#24283b", fg = "#1d546a" })
hi(0, "NotifyINFOIcon", { fg = "#0db9d7" })
hi(0, "NotifyINFOTitle", { fg = "#0db9d7" })
hi(0, "NotifyTRACEBody", { bg = "#24283b", fg = "#c0caf5" })
hi(0, "NotifyTRACEBorder", { bg = "#24283b", fg = "#48416a" })
hi(0, "NotifyTRACEIcon", { fg = "#9d7cd8" })
hi(0, "NotifyTRACETitle", { fg = "#9d7cd8" })
hi(0, "NotifyWARNBody", { bg = "#24283b", fg = "#c0caf5" })
hi(0, "NotifyWARNBorder", { bg = "#24283b", fg = "#5c5149" })
hi(0, "NotifyWARNIcon", { fg = "#e0af68" })
hi(0, "NotifyWARNTitle", { fg = "#e0af68" })
hi(0, "NvimTreeFolderIcon", { fg = "#7aa2f7" })
hi(0, "NvimTreeGitDeleted", { fg = "#914c54" })
hi(0, "NvimTreeGitDirty", { fg = "#6183bb" })
hi(0, "NvimTreeGitNew", { fg = "#449dab" })
hi(0, "NvimTreeImageFile", { fg = "#a9b1d6" })
hi(0, "NvimTreeIndentMarker", { fg = "#3b4261" })
hi(0, "NvimTreeNormal", { bg = "#1f2335", fg = "#a9b1d6" })
hi(0, "NvimTreeNormalNC", { bg = "#1f2335", fg = "#a9b1d6" })
hi(0, "NvimTreeOpenedFile", { bg = "#292e42" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#7aa2f7" })
hi(0, "NvimTreeSpecialFile", { fg = "#9d7cd8", underline = true })
hi(0, "NvimTreeSymlink", { fg = "#7aa2f7" })
hi(0, "NvimTreeWinSeparator", { bg = "#1f2335", fg = "#1f2335" })
hi(0, "OctoDetailsLabel", { bold = true, fg = "#2ac3de" })
hi(0, "OctoDetailsValue", { link = "@variable.member" })
hi(0, "OctoDirty", { bold = true, fg = "#ff9e64" })
hi(0, "OctoIssueTitle", { bold = true, fg = "#9d7cd8" })
hi(0, "OctoStateChangesRequested", { link = "DiagnosticVirtualTextWarn" })
hi(0, "OctoStateClosed", { link = "DiagnosticVirtualTextError" })
hi(0, "OctoStateMerged", { bg = "#33334e", fg = "#bb9af7" })
hi(0, "OctoStateOpen", { link = "DiagnosticVirtualTextHint" })
hi(0, "OctoStatePending", { link = "DiagnosticVirtualTextWarn" })
hi(0, "OctoStatusColumn", { fg = "#2ac3de" })
hi(0, "Operator", { fg = "#89ddff" })
hi(0, "Pmenu", { bg = "#1f2335", fg = "#c0caf5" })
hi(0, "PmenuMatch", { bg = "#1f2335", fg = "#2ac3de" })
hi(0, "PmenuMatchSel", { bg = "#363d59", fg = "#2ac3de" })
hi(0, "PmenuSbar", { bg = "#272b3f" })
hi(0, "PmenuSel", { bg = "#363d59" })
hi(0, "PmenuThumb", { bg = "#3b4261" })
hi(0, "PreProc", { fg = "#7dcfff" })
hi(0, "Question", { fg = "#7aa2f7" })
hi(0, "QuickFixLine", { bg = "#2e3c64", bold = true })
hi(0, "RainbowDelimiterBlue", { fg = "#7aa2f7" })
hi(0, "RainbowDelimiterCyan", { fg = "#7dcfff" })
hi(0, "RainbowDelimiterGreen", { fg = "#9ece6a" })
hi(0, "RainbowDelimiterOrange", { fg = "#ff9e64" })
hi(0, "RainbowDelimiterRed", { fg = "#f7768e" })
hi(0, "RainbowDelimiterViolet", { fg = "#9d7cd8" })
hi(0, "RainbowDelimiterYellow", { fg = "#e0af68" })
hi(0, "ReferencesCount", { fg = "#9d7cd8" })
hi(0, "ReferencesIcon", { fg = "#7aa2f7" })
hi(0, "RenderMarkdownBullet", { fg = "#ff9e64" })
hi(0, "RenderMarkdownCode", { bg = "#1f2335" })
hi(0, "RenderMarkdownCodeInline", { link = "@markup.raw.markdown_inline" })
hi(0, "RenderMarkdownDash", { fg = "#ff9e64" })
hi(0, "RenderMarkdownH1Bg", { bg = "#2d344e" })
hi(0, "RenderMarkdownH1Fg", { bold = true, fg = "#7aa2f7" })
hi(0, "RenderMarkdownH2Bg", { bg = "#373640" })
hi(0, "RenderMarkdownH2Fg", { bold = true, fg = "#e0af68" })
hi(0, "RenderMarkdownH3Bg", { bg = "#303940" })
hi(0, "RenderMarkdownH3Fg", { bold = true, fg = "#9ece6a" })
hi(0, "RenderMarkdownH4Bg", { bg = "#233745" })
hi(0, "RenderMarkdownH4Fg", { bold = true, fg = "#1abc9c" })
hi(0, "RenderMarkdownH5Bg", { bg = "#33334e" })
hi(0, "RenderMarkdownH5Fg", { bold = true, fg = "#bb9af7" })
hi(0, "RenderMarkdownH6Bg", { bg = "#30304b" })
hi(0, "RenderMarkdownH6Fg", { bold = true, fg = "#9d7cd8" })
hi(0, "RenderMarkdownH7Bg", { bg = "#3a343f" })
hi(0, "RenderMarkdownH7Fg", { bold = true, fg = "#ff9e64" })
hi(0, "RenderMarkdownH8Bg", { bg = "#393043" })
hi(0, "RenderMarkdownH8Fg", { bold = true, fg = "#f7768e" })
hi(0, "RenderMarkdownTableHead", { fg = "#f7768e" })
hi(0, "RenderMarkdownTableRow", { fg = "#ff9e64" })
hi(0, "ScrollbarError", { fg = "#db4b4b" })
hi(0, "ScrollbarErrorHandle", { bg = "#292e42", fg = "#db4b4b" })
hi(0, "ScrollbarHandle", { bg = "#292e42" })
hi(0, "ScrollbarHint", { fg = "#1abc9c" })
hi(0, "ScrollbarHintHandle", { bg = "#292e42", fg = "#1abc9c" })
hi(0, "ScrollbarInfo", { fg = "#0db9d7" })
hi(0, "ScrollbarInfoHandle", { bg = "#292e42", fg = "#0db9d7" })
hi(0, "ScrollbarMisc", { fg = "#9d7cd8" })
hi(0, "ScrollbarMiscHandle", { bg = "#292e42", fg = "#9d7cd8" })
hi(0, "ScrollbarSearch", { fg = "#ff9e64" })
hi(0, "ScrollbarSearchHandle", { bg = "#292e42", fg = "#ff9e64" })
hi(0, "ScrollbarWarn", { fg = "#e0af68" })
hi(0, "ScrollbarWarnHandle", { bg = "#292e42", fg = "#e0af68" })
hi(0, "Search", { bg = "#3d59a1", fg = "#c0caf5" })
hi(0, "SignColumn", { bg = "#24283b", fg = "#3b4261" })
hi(0, "SignColumnSB", { bg = "#1f2335", fg = "#3b4261" })
hi(0, "SnacksDashboardDesc", { fg = "#7dcfff" })
hi(0, "SnacksDashboardDir", { fg = "#545c7e" })
hi(0, "SnacksDashboardFooter", { fg = "#2ac3de" })
hi(0, "SnacksDashboardHeader", { fg = "#7aa2f7" })
hi(0, "SnacksDashboardIcon", { fg = "#2ac3de" })
hi(0, "SnacksDashboardKey", { fg = "#ff9e64" })
hi(0, "SnacksDashboardSpecial", { fg = "#9d7cd8" })
hi(0, "SnacksIndent", { fg = "#3b4261", nocombine = true })
hi(0, "SnacksIndent1", { fg = "#7aa2f7", nocombine = true })
hi(0, "SnacksIndent2", { fg = "#e0af68", nocombine = true })
hi(0, "SnacksIndent3", { fg = "#9ece6a", nocombine = true })
hi(0, "SnacksIndent4", { fg = "#1abc9c", nocombine = true })
hi(0, "SnacksIndent5", { fg = "#bb9af7", nocombine = true })
hi(0, "SnacksIndent6", { fg = "#9d7cd8", nocombine = true })
hi(0, "SnacksIndent7", { fg = "#ff9e64", nocombine = true })
hi(0, "SnacksIndent8", { fg = "#f7768e", nocombine = true })
hi(0, "SnacksIndentScope", { fg = "#2ac3de", nocombine = true })
hi(0, "SnacksInputBorder", { fg = "#e0af68" })
hi(0, "SnacksInputIcon", { fg = "#2ac3de" })
hi(0, "SnacksInputTitle", { fg = "#e0af68" })
hi(0, "SnacksNotifierBorderDebug", { bg = "#24283b", fg = "#383e5a" })
hi(0, "SnacksNotifierBorderError", { bg = "#24283b", fg = "#6d3641" })
hi(0, "SnacksNotifierBorderInfo", { bg = "#24283b", fg = "#1b6279" })
hi(0, "SnacksNotifierBorderTrace", { bg = "#24283b", fg = "#544a7a" })
hi(0, "SnacksNotifierBorderWarn", { bg = "#24283b", fg = "#6f5e4d" })
hi(0, "SnacksNotifierDebug", { bg = "#24283b", fg = "#c0caf5" })
hi(0, "SnacksNotifierError", { bg = "#24283b", fg = "#c0caf5" })
hi(0, "SnacksNotifierIconDebug", { fg = "#565f89" })
hi(0, "SnacksNotifierIconError", { fg = "#db4b4b" })
hi(0, "SnacksNotifierIconInfo", { fg = "#0db9d7" })
hi(0, "SnacksNotifierIconTrace", { fg = "#9d7cd8" })
hi(0, "SnacksNotifierIconWarn", { fg = "#e0af68" })
hi(0, "SnacksNotifierInfo", { bg = "#24283b", fg = "#c0caf5" })
hi(0, "SnacksNotifierTitleDebug", { fg = "#565f89" })
hi(0, "SnacksNotifierTitleError", { fg = "#db4b4b" })
hi(0, "SnacksNotifierTitleInfo", { fg = "#0db9d7" })
hi(0, "SnacksNotifierTitleTrace", { fg = "#9d7cd8" })
hi(0, "SnacksNotifierTitleWarn", { fg = "#e0af68" })
hi(0, "SnacksNotifierTrace", { bg = "#24283b", fg = "#c0caf5" })
hi(0, "SnacksNotifierWarn", { bg = "#24283b", fg = "#c0caf5" })
hi(0, "SnacksPickerBoxTitle", { bg = "#1f2335", fg = "#ff9e64" })
hi(0, "SnacksPickerInputBorder", { bg = "#1f2335", fg = "#ff9e64" })
hi(0, "SnacksPickerInputTitle", { bg = "#1f2335", fg = "#ff9e64" })
hi(0, "SnacksPickerPickWin", { bg = "#3d59a1", bold = true, fg = "#c0caf5" })
hi(0, "SnacksPickerPickWinCurrent", { bg = "#ff007c", bold = true, fg = "#c0caf5" })
hi(0, "SnacksPickerSelected", { fg = "#ff007c" })
hi(0, "SnacksPickerToggle", { link = "SnacksProfilerBadgeInfo" })
hi(0, "SnacksProfilerBadgeInfo", { bg = "#25384b", fg = "#2ac3de" })
hi(0, "SnacksProfilerBadgeTrace", { bg = "#262c40", fg = "#545c7e" })
hi(0, "SnacksProfilerIconInfo", { bg = "#26576c", fg = "#2ac3de" })
hi(0, "SnacksProfilerIconTrace", { bg = "#2a334b", fg = "#545c7e" })
hi(0, "SnacksScratchDesc", { link = "SnacksProfilerBadgeInfo" })
hi(0, "SnacksScratchKey", { link = "SnacksProfilerIconInfo" })
hi(0, "SnacksZenIcon", { fg = "#9d7cd8" })
hi(0, "Sneak", { bg = "#bb9af7", fg = "#292e42" })
hi(0, "SneakScope", { bg = "#2e3c64" })
hi(0, "Special", { fg = "#2ac3de" })
hi(0, "SpecialKey", { fg = "#545c7e" })
hi(0, "SpellBad", { sp = "#db4b4b", undercurl = true })
hi(0, "SpellCap", { sp = "#e0af68", undercurl = true })
hi(0, "SpellLocal", { sp = "#0db9d7", undercurl = true })
hi(0, "SpellRare", { sp = "#1abc9c", undercurl = true })
hi(0, "Statement", { fg = "#bb9af7" })
hi(0, "StatusLine", { bg = "#1f2335", fg = "#a9b1d6" })
hi(0, "StatusLineNC", { bg = "#1f2335", fg = "#3b4261" })
hi(0, "String", { fg = "#9ece6a" })
hi(0, "Substitute", { bg = "#f7768e", fg = "#1d202f" })
hi(0, "SupermavenSuggestion", { fg = "#414868" })
hi(0, "TabLine", { bg = "#1f2335", fg = "#3b4261" })
hi(0, "TabLineFill", { bg = "#1d202f" })
hi(0, "TabLineSel", { bg = "#7aa2f7", fg = "#1d202f" })
hi(0, "TargetWord", { fg = "#7dcfff" })
hi(0, "TelescopeBorder", { bg = "#1f2335", fg = "#29a4bd" })
hi(0, "TelescopeNormal", { bg = "#1f2335", fg = "#c0caf5" })
hi(0, "TelescopePromptBorder", { bg = "#1f2335", fg = "#ff9e64" })
hi(0, "TelescopePromptTitle", { bg = "#1f2335", fg = "#ff9e64" })
hi(0, "TelescopeResultsComment", { fg = "#545c7e" })
hi(0, "Title", { bold = true, fg = "#7aa2f7" })
hi(0, "Todo", { bg = "#e0af68", fg = "#24283b" })
hi(0, "TreesitterContext", { bg = "#363d59" })
hi(0, "TroubleCount", { bg = "#3b4261", fg = "#bb9af7" })
hi(0, "TroubleNormal", { bg = "#1f2335", fg = "#c0caf5" })
hi(0, "TroubleText", { fg = "#a9b1d6" })
hi(0, "Type", { fg = "#2ac3de" })
hi(0, "VertSplit", { fg = "#1d202f" })
hi(0, "VimwikiHR", { fg = "#e0af68" })
hi(0, "VimwikiHeader1", { bold = true, fg = "#7aa2f7" })
hi(0, "VimwikiHeader2", { bold = true, fg = "#e0af68" })
hi(0, "VimwikiHeader3", { bold = true, fg = "#9ece6a" })
hi(0, "VimwikiHeader4", { bold = true, fg = "#1abc9c" })
hi(0, "VimwikiHeader5", { bold = true, fg = "#bb9af7" })
hi(0, "VimwikiHeader6", { bold = true, fg = "#9d7cd8" })
hi(0, "VimwikiHeader7", { bold = true, fg = "#ff9e64" })
hi(0, "VimwikiHeader8", { bold = true, fg = "#f7768e" })
hi(0, "VimwikiHeaderChar", { fg = "#e0af68" })
hi(0, "VimwikiLink", { fg = "#7aa2f7" })
hi(0, "VimwikiList", { fg = "#ff9e64" })
hi(0, "VimwikiMarkers", { fg = "#7aa2f7" })
hi(0, "VimwikiTag", { fg = "#9ece6a" })
hi(0, "Visual", { bg = "#2e3c64" })
hi(0, "VisualNOS", { bg = "#2e3c64" })
hi(0, "WarningMsg", { fg = "#e0af68" })
hi(0, "WhichKey", { fg = "#7dcfff" })
hi(0, "WhichKeyDesc", { fg = "#bb9af7" })
hi(0, "WhichKeyGroup", { fg = "#7aa2f7" })
hi(0, "WhichKeyNormal", { bg = "#1f2335" })
hi(0, "WhichKeySeparator", { fg = "#565f89" })
hi(0, "WhichKeyValue", { fg = "#737aa2" })
hi(0, "Whitespace", { fg = "#3b4261" })
hi(0, "WildMenu", { bg = "#2e3c64" })
hi(0, "WinBar", { link = "StatusLine" })
hi(0, "WinBarNC", { link = "StatusLineNC" })
hi(0, "WinSeparator", { bold = true, fg = "#1d202f" })
hi(0, "YankyPut", { link = "Search" })
hi(0, "YankyYanked", { link = "IncSearch" })
hi(0, "debugBreakpoint", { bg = "#22374b", fg = "#0db9d7" })
hi(0, "debugPC", { bg = "#1f2335" })
hi(0, "diffAdded", { bg = "#283b4d", fg = "#449dab" })
hi(0, "diffChanged", { bg = "#272d43", fg = "#6183bb" })
hi(0, "diffFile", { fg = "#7aa2f7" })
hi(0, "diffIndexLine", { fg = "#bb9af7" })
hi(0, "diffLine", { fg = "#565f89" })
hi(0, "diffNewFile", { bg = "#283b4d", fg = "#2ac3de" })
hi(0, "diffOldFile", { bg = "#3f2d3d", fg = "#2ac3de" })
hi(0, "diffRemoved", { bg = "#3f2d3d", fg = "#914c54" })
hi(0, "dosiniLabel", { link = "@property" })
hi(0, "healthError", { fg = "#db4b4b" })
hi(0, "healthSuccess", { fg = "#73daca" })
hi(0, "healthWarning", { fg = "#e0af68" })
hi(0, "helpCommand", { bg = "#414868", fg = "#7aa2f7" })
hi(0, "helpExample", { fg = "#565f89" })
hi(0, "htmlH1", { bold = true, fg = "#bb9af7" })
hi(0, "htmlH2", { bold = true, fg = "#7aa2f7" })
hi(0, "illuminatedCurWord", { bg = "#3b4261" })
hi(0, "illuminatedWord", { bg = "#3b4261" })
hi(0, "lCursor", { bg = "#c0caf5", fg = "#24283b" })
hi(0, "qfFileName", { fg = "#7aa2f7" })
hi(0, "qfLineNr", { fg = "#737aa2" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#1d202f"
g.terminal_color_1 = "#f7768e"
g.terminal_color_2 = "#9ece6a"
g.terminal_color_3 = "#e0af68"
g.terminal_color_4 = "#7aa2f7"
g.terminal_color_5 = "#bb9af7"
g.terminal_color_6 = "#7dcfff"
g.terminal_color_7 = "#a9b1d6"
g.terminal_color_8 = "#414868"
g.terminal_color_9 = "#ff899d"
g.terminal_color_10 = "#9fe044"
g.terminal_color_11 = "#faba4a"
g.terminal_color_12 = "#8db0ff"
g.terminal_color_13 = "#c7a9ff"
g.terminal_color_14 = "#a4daff"
g.terminal_color_15 = "#c0caf5"
